<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Ricis.Resources/Ricis.Resources.csproj" />
    <Compile Remove="Ricis.Numerics.UnitTests/**/*.cs" />
    <None Remove="Ricis.Numerics.UnitTests/**" />
    <Compile Remove="Ricis.Numerics.Benchmarks/**/*.cs" />
    <None Remove="Ricis.Numerics.Benchmarks/**" />
  </ItemGroup>
</Project>
