<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);1591</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup>
    <PublishAot>true</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="RegressionTests/**/*.cs" />
    <Compile Remove="Ricis.Console/**/*.cs" />
    <Compile Remove="Ricis.NavierStokes.Console/**/*.cs" />
  </ItemGroup>

</Project>
