<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssetTargetFallback>net8.0-windows;net48;net472</AssetTargetFallback>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit.Wpf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ricis.Core.csproj" />
    <ProjectReference Include="..\Ricis.Kinematics\Ricis.Kinematics.csproj" />
  </ItemGroup>

</Project>
