events { }
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        # Cloud Run передает порт через переменную окружения $PORT. 
        # Nginx должен слушать именно его (по умолчанию в Cloud Run это 8080).
        listen 8080;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }
}