using System.Linq.Expressions;
using System.Numerics;
using System.Text;
using Ricis.Core.Extensions;
using Ricis.Core.Proofs;
using Ricis.Core.Solvers.Fermat;

internal static class RicisFermatSystemSuite
{
    public static IEnumerable<(string Name, Action Body)> Tests =>
    [
        ("FERMAT01: RICIS решает общую систему только по N и пишет штатный Log", NOnlySystemUsesProofLog),
        ("FERMAT02: универсальный Log принимает F=x² и доказывает F/F=1", UniversalDeferredIdentityUsesLog),
        ("FERMAT03: public Solve возвращает точную ферматову реконструкцию", DirectSolveRetainsExactInvariants),
        ("FERMAT04: public Solve принимает все классы квадратов modulo 64", SolveAcceptsEverySquareResidueClass),
    ];

    private static void NOnlySystemUsesProofLog()
    {
        var n = BigInteger.Parse("1700000020900000063");
        var profile = new RicisProofDocumentProfile(
            title: "RICIS III: N-only Fermat system",
            scope: RicisProofScope.FiniteDerivation,
            @abstract: "The solver receives only N and derives the difference-of-squares factorization.",
            theorem: $"For N={n}, the solver derives P·Q=N and x²−N=y².",
            definitions:
            [
                "N is the only numeric input.",
                "P and Q are solver outputs reconstructed as x−y and x+y.",
                "All normalization exponents are derived from the actual BigInteger result."
            ],
            axioms:
            [
                "Difference-of-squares reconstruction is recorded as a finite RICIS derivation."
            ],
            limitations:
            [
                "The document reports the finite solver derivation for this supplied N."
            ]);
        var document = new StringBuilder();

        var result = FermatFactorizer.ProveDocument(
            n,
            profile,
            RicisProofDocumentFormat.Log,
            document);

        Console.WriteLine(document.ToString());

        Require(result.N == n, "Solver must preserve the only input N.");
        Require(result.P * result.Q == n, "Factorization must be checked only by P·Q=N.");
        Require(result.X * result.X - n == result.Y * result.Y,
            "The solver result must satisfy x²−N=y².");
        Require(result.X - result.Y == result.P && result.X + result.Y == result.Q,
            "The structural substitutions P=x−y and Q=x+y must close.");
        Require(result.InputBitLength == n.GetBitLength(),
            "Input bit length must be derived from the actual N value and type.");
        Require(result.FactorBitLength == Math.Max(result.P.GetBitLength(), result.Q.GetBitLength()),
            "Factor bit length must be derived from the found P and Q.");
        Require(result.FactorScale == (BigInteger.One << result.FactorBitLength),
            "Factor scale must be dynamically derived from factor bit length.");

        var proof = document.ToString();
        Require(proof.Contains("[RICIS FiniteDerivation]", StringComparison.Ordinal) &&
                proof.Contains("trace:", StringComparison.Ordinal) &&
                proof.Contains("N-only input", StringComparison.Ordinal) &&
                proof.Contains("Difference recurrence", StringComparison.Ordinal) &&
                proof.Contains("Substitution", StringComparison.Ordinal) &&
                proof.Contains("Reconstruction check", StringComparison.Ordinal) &&
                proof.Contains("Dynamic normalization", StringComparison.Ordinal),
            "The simple Log must be generated by ProveDocument and contain the solver trace.");
    }

    private static void DirectSolveRetainsExactInvariants()
    {
        var n = new BigInteger(5959); // 59 × 101 = (80−21)(80+21)

        var result = FermatFactorizer.Solve(n);

        Require(result.N == n && result.P * result.Q == n,
            "Public Solve обязан вернуть проверяемую факторизацию P·Q=N.");
        Require(result.X * result.X - result.N == result.Y * result.Y,
            "Public Solve обязан сохранить точное равенство x²−N=y².");
        Require(result.X - result.Y == result.P && result.X + result.Y == result.Q,
            "Public Solve обязан сохранить структурные подстановки P=x−y и Q=x+y.");
    }

    private static void SolveAcceptsEverySquareResidueClass()
    {
        // Each pair is semiprime and realizes a distinct y² modulo 64 class:
        // { 0, 1, 4, 9, 16, 17, 25, 33, 36, 41, 49, 57 }.
        (int P, int Q)[] factorPairs =
        [
            (101, 101), (101, 103), (103, 107), (101, 107),
            (101, 109), (103, 113), (101, 113), (113, 127),
            (109, 127), (109, 131), (101, 127), (101, 131),
        ];
        var observedResidues = new HashSet<int>();

        foreach (var (p, q) in factorPairs)
        {
            var result = FermatFactorizer.Solve(new BigInteger(p * q));
            observedResidues.Add((int)((result.Y * result.Y) & 63));
            Require(result.P * result.Q == result.N && result.X * result.X - result.N == result.Y * result.Y,
                $"Public Solve обязан сохранить exact reconstruction для {p}·{q}.");
        }

        Require(observedResidues.SetEquals([0, 1, 4, 9, 16, 17, 25, 33, 36, 41, 49, 57]),
            $"Fermat examples должны покрыть все exact square residue classes modulo 64, получено [{string.Join(", ", observedResidues.Order())}].");
    }

    private static void UniversalDeferredIdentityUsesLog()
    {
        Expression<Func<double, bool>>[] conditions = [];
        Expression<Func<double, bool>>[] constraints = [];
        Expression<Func<double, double>> claim = x => (x * x) / (x * x);
        var profile = new RicisProofDocumentProfile(
            title: "RICIS III: universal deferred F/F",
            scope: RicisProofScope.FiniteDerivation,
            @abstract: "A nonlinear deferred F is handled structurally without a linear-system restriction.",
            theorem: "For F=x², the identity F/F=1 is derived by RICIS.",
            definitions: ["F is the deferred expression x²."],
            axioms: ["L1: identical entity divided by itself is 1."],
            limitations: ["The Log records the finite structural derivation."]);
        var document = new StringBuilder();
        var derived = conditions.ProveDocument(
            constraints,
            claim,
            profile,
            RicisProofDocumentFormat.Log,
            document);
        var proof = document.ToString();
        Require(derived.Compile()(3.0) == 1.0,
            "Для F=x² generic ProveDocument должен вывести F/F=1.");
        Require(proof.Contains("universal deferred F/F", StringComparison.Ordinal) &&
                proof.Contains("trace:", StringComparison.Ordinal) &&
                proof.Contains("F=x²", StringComparison.Ordinal),
            "Универсальный Log должен содержать nonlinear F и RICIS trace.");
    }

    private static void Require(bool condition, string message)
    {
        if (!condition) throw new InvalidOperationException(message);
    }
}
