// <auto-generated />
// Generated by scripts/generate_ulong2048_integral_operators.py. Do not hand edit.
#nullable enable

using System.Numerics;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Ricis.Numerics.UnitTests;

[TestClass]
public sealed class ULong2048IntegralOperatorsGeneratedSuite
{
    private static readonly BigInteger Modulus = BigInteger.One << 2048;
    private static readonly ULong2048 Value = ULong2048.FromBigInteger((BigInteger.One << 160) + 12345);
    private static readonly BigInteger ValueBigInteger = Value.ToBigInteger();
    private static BigInteger B(ULong2048 value) => value.ToBigInteger();
    private static BigInteger Wrap(BigInteger value)
    {
        value %= Modulus;
        return value.Sign < 0 ? value + Modulus : value;
    }

    [TestMethod("U2048-INTEGRAL-U01: byte symmetric arithmetic bitwise comparison checked and shifts")]
    public void Unsigned_byte_Operators()
    {
        byte operand = (byte)7;
        var operandBigInteger = new BigInteger(7);
        Assert.AreEqual(Wrap(ValueBigInteger + operandBigInteger), B(Value + operand));
        Assert.AreEqual(Wrap(operandBigInteger + ValueBigInteger), B(operand + Value));
        Assert.AreEqual(Wrap(ValueBigInteger - operandBigInteger), B(Value - operand));
        Assert.AreEqual(Wrap(operandBigInteger - ValueBigInteger), B(operand - Value));
        Assert.AreEqual(Wrap(ValueBigInteger * operandBigInteger), B(Value * operand));
        Assert.AreEqual(Wrap(operandBigInteger * ValueBigInteger), B(operand * Value));
        Assert.AreEqual(ValueBigInteger / operandBigInteger, B(Value / operand));
        Assert.AreEqual(operandBigInteger / ValueBigInteger, B(operand / Value));
        Assert.AreEqual(ValueBigInteger % operandBigInteger, B(Value % operand));
        Assert.AreEqual(operandBigInteger % ValueBigInteger, B(operand % Value));
        Assert.AreEqual(ValueBigInteger & operandBigInteger, B(Value & operand));
        Assert.AreEqual(operandBigInteger & ValueBigInteger, B(operand & Value));
        Assert.AreEqual(ValueBigInteger | operandBigInteger, B(Value | operand));
        Assert.AreEqual(operandBigInteger | ValueBigInteger, B(operand | Value));
        Assert.AreEqual(ValueBigInteger ^ operandBigInteger, B(Value ^ operand));
        Assert.AreEqual(operandBigInteger ^ ValueBigInteger, B(operand ^ Value));
        Assert.IsTrue(Value > operand && operand < Value && Value != operand && operand != Value);
        Assert.AreEqual(Value << 7, Value << operand);
        Assert.AreEqual(Value >> 7, Value >> operand);
        Assert.AreEqual(Value >>> 7, Value >>> operand);
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue + operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.Zero - operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue * operand));
    }

    [TestMethod("U2048-INTEGRAL-U02: ushort symmetric arithmetic bitwise comparison checked and shifts")]
    public void Unsigned_ushort_Operators()
    {
        ushort operand = (ushort)7;
        var operandBigInteger = new BigInteger(7);
        Assert.AreEqual(Wrap(ValueBigInteger + operandBigInteger), B(Value + operand));
        Assert.AreEqual(Wrap(operandBigInteger + ValueBigInteger), B(operand + Value));
        Assert.AreEqual(Wrap(ValueBigInteger - operandBigInteger), B(Value - operand));
        Assert.AreEqual(Wrap(operandBigInteger - ValueBigInteger), B(operand - Value));
        Assert.AreEqual(Wrap(ValueBigInteger * operandBigInteger), B(Value * operand));
        Assert.AreEqual(Wrap(operandBigInteger * ValueBigInteger), B(operand * Value));
        Assert.AreEqual(ValueBigInteger / operandBigInteger, B(Value / operand));
        Assert.AreEqual(operandBigInteger / ValueBigInteger, B(operand / Value));
        Assert.AreEqual(ValueBigInteger % operandBigInteger, B(Value % operand));
        Assert.AreEqual(operandBigInteger % ValueBigInteger, B(operand % Value));
        Assert.AreEqual(ValueBigInteger & operandBigInteger, B(Value & operand));
        Assert.AreEqual(operandBigInteger & ValueBigInteger, B(operand & Value));
        Assert.AreEqual(ValueBigInteger | operandBigInteger, B(Value | operand));
        Assert.AreEqual(operandBigInteger | ValueBigInteger, B(operand | Value));
        Assert.AreEqual(ValueBigInteger ^ operandBigInteger, B(Value ^ operand));
        Assert.AreEqual(operandBigInteger ^ ValueBigInteger, B(operand ^ Value));
        Assert.IsTrue(Value > operand && operand < Value && Value != operand && operand != Value);
        Assert.AreEqual(Value << 7, Value << operand);
        Assert.AreEqual(Value >> 7, Value >> operand);
        Assert.AreEqual(Value >>> 7, Value >>> operand);
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue + operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.Zero - operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue * operand));
    }

    [TestMethod("U2048-INTEGRAL-U03: uint symmetric arithmetic bitwise comparison checked and shifts")]
    public void Unsigned_uint_Operators()
    {
        uint operand = 7u;
        var operandBigInteger = new BigInteger(7);
        Assert.AreEqual(Wrap(ValueBigInteger + operandBigInteger), B(Value + operand));
        Assert.AreEqual(Wrap(operandBigInteger + ValueBigInteger), B(operand + Value));
        Assert.AreEqual(Wrap(ValueBigInteger - operandBigInteger), B(Value - operand));
        Assert.AreEqual(Wrap(operandBigInteger - ValueBigInteger), B(operand - Value));
        Assert.AreEqual(Wrap(ValueBigInteger * operandBigInteger), B(Value * operand));
        Assert.AreEqual(Wrap(operandBigInteger * ValueBigInteger), B(operand * Value));
        Assert.AreEqual(ValueBigInteger / operandBigInteger, B(Value / operand));
        Assert.AreEqual(operandBigInteger / ValueBigInteger, B(operand / Value));
        Assert.AreEqual(ValueBigInteger % operandBigInteger, B(Value % operand));
        Assert.AreEqual(operandBigInteger % ValueBigInteger, B(operand % Value));
        Assert.AreEqual(ValueBigInteger & operandBigInteger, B(Value & operand));
        Assert.AreEqual(operandBigInteger & ValueBigInteger, B(operand & Value));
        Assert.AreEqual(ValueBigInteger | operandBigInteger, B(Value | operand));
        Assert.AreEqual(operandBigInteger | ValueBigInteger, B(operand | Value));
        Assert.AreEqual(ValueBigInteger ^ operandBigInteger, B(Value ^ operand));
        Assert.AreEqual(operandBigInteger ^ ValueBigInteger, B(operand ^ Value));
        Assert.IsTrue(Value > operand && operand < Value && Value != operand && operand != Value);
        Assert.AreEqual(Value << 7, Value << operand);
        Assert.AreEqual(Value >> 7, Value >> operand);
        Assert.AreEqual(Value >>> 7, Value >>> operand);
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue + operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.Zero - operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue * operand));
    }

    [TestMethod("U2048-INTEGRAL-U04: ulong symmetric arithmetic bitwise comparison checked and shifts")]
    public void Unsigned_ulong_Operators()
    {
        ulong operand = 7ul;
        var operandBigInteger = new BigInteger(7);
        Assert.AreEqual(Wrap(ValueBigInteger + operandBigInteger), B(Value + operand));
        Assert.AreEqual(Wrap(operandBigInteger + ValueBigInteger), B(operand + Value));
        Assert.AreEqual(Wrap(ValueBigInteger - operandBigInteger), B(Value - operand));
        Assert.AreEqual(Wrap(operandBigInteger - ValueBigInteger), B(operand - Value));
        Assert.AreEqual(Wrap(ValueBigInteger * operandBigInteger), B(Value * operand));
        Assert.AreEqual(Wrap(operandBigInteger * ValueBigInteger), B(operand * Value));
        Assert.AreEqual(ValueBigInteger / operandBigInteger, B(Value / operand));
        Assert.AreEqual(operandBigInteger / ValueBigInteger, B(operand / Value));
        Assert.AreEqual(ValueBigInteger % operandBigInteger, B(Value % operand));
        Assert.AreEqual(operandBigInteger % ValueBigInteger, B(operand % Value));
        Assert.AreEqual(ValueBigInteger & operandBigInteger, B(Value & operand));
        Assert.AreEqual(operandBigInteger & ValueBigInteger, B(operand & Value));
        Assert.AreEqual(ValueBigInteger | operandBigInteger, B(Value | operand));
        Assert.AreEqual(operandBigInteger | ValueBigInteger, B(operand | Value));
        Assert.AreEqual(ValueBigInteger ^ operandBigInteger, B(Value ^ operand));
        Assert.AreEqual(operandBigInteger ^ ValueBigInteger, B(operand ^ Value));
        Assert.IsTrue(Value > operand && operand < Value && Value != operand && operand != Value);
        Assert.AreEqual(Value << 7, Value << operand);
        Assert.AreEqual(Value >> 7, Value >> operand);
        Assert.AreEqual(Value >>> 7, Value >>> operand);
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue + operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.Zero - operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue * operand));
    }

    [TestMethod("U2048-INTEGRAL-U05: nuint symmetric arithmetic bitwise comparison checked and shifts")]
    public void Unsigned_nuint_Operators()
    {
        nuint operand = (nuint)7;
        var operandBigInteger = new BigInteger(7);
        Assert.AreEqual(Wrap(ValueBigInteger + operandBigInteger), B(Value + operand));
        Assert.AreEqual(Wrap(operandBigInteger + ValueBigInteger), B(operand + Value));
        Assert.AreEqual(Wrap(ValueBigInteger - operandBigInteger), B(Value - operand));
        Assert.AreEqual(Wrap(operandBigInteger - ValueBigInteger), B(operand - Value));
        Assert.AreEqual(Wrap(ValueBigInteger * operandBigInteger), B(Value * operand));
        Assert.AreEqual(Wrap(operandBigInteger * ValueBigInteger), B(operand * Value));
        Assert.AreEqual(ValueBigInteger / operandBigInteger, B(Value / operand));
        Assert.AreEqual(operandBigInteger / ValueBigInteger, B(operand / Value));
        Assert.AreEqual(ValueBigInteger % operandBigInteger, B(Value % operand));
        Assert.AreEqual(operandBigInteger % ValueBigInteger, B(operand % Value));
        Assert.AreEqual(ValueBigInteger & operandBigInteger, B(Value & operand));
        Assert.AreEqual(operandBigInteger & ValueBigInteger, B(operand & Value));
        Assert.AreEqual(ValueBigInteger | operandBigInteger, B(Value | operand));
        Assert.AreEqual(operandBigInteger | ValueBigInteger, B(operand | Value));
        Assert.AreEqual(ValueBigInteger ^ operandBigInteger, B(Value ^ operand));
        Assert.AreEqual(operandBigInteger ^ ValueBigInteger, B(operand ^ Value));
        Assert.IsTrue(Value > operand && operand < Value && Value != operand && operand != Value);
        Assert.AreEqual(Value << 7, Value << operand);
        Assert.AreEqual(Value >> 7, Value >> operand);
        Assert.AreEqual(Value >>> 7, Value >>> operand);
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue + operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.Zero - operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue * operand));
    }

    [TestMethod("U2048-INTEGRAL-U06: UInt128 symmetric arithmetic bitwise comparison checked and shifts")]
    public void Unsigned_UInt128_Operators()
    {
        UInt128 operand = (UInt128)7;
        var operandBigInteger = new BigInteger(7);
        Assert.AreEqual(Wrap(ValueBigInteger + operandBigInteger), B(Value + operand));
        Assert.AreEqual(Wrap(operandBigInteger + ValueBigInteger), B(operand + Value));
        Assert.AreEqual(Wrap(ValueBigInteger - operandBigInteger), B(Value - operand));
        Assert.AreEqual(Wrap(operandBigInteger - ValueBigInteger), B(operand - Value));
        Assert.AreEqual(Wrap(ValueBigInteger * operandBigInteger), B(Value * operand));
        Assert.AreEqual(Wrap(operandBigInteger * ValueBigInteger), B(operand * Value));
        Assert.AreEqual(ValueBigInteger / operandBigInteger, B(Value / operand));
        Assert.AreEqual(operandBigInteger / ValueBigInteger, B(operand / Value));
        Assert.AreEqual(ValueBigInteger % operandBigInteger, B(Value % operand));
        Assert.AreEqual(operandBigInteger % ValueBigInteger, B(operand % Value));
        Assert.AreEqual(ValueBigInteger & operandBigInteger, B(Value & operand));
        Assert.AreEqual(operandBigInteger & ValueBigInteger, B(operand & Value));
        Assert.AreEqual(ValueBigInteger | operandBigInteger, B(Value | operand));
        Assert.AreEqual(operandBigInteger | ValueBigInteger, B(operand | Value));
        Assert.AreEqual(ValueBigInteger ^ operandBigInteger, B(Value ^ operand));
        Assert.AreEqual(operandBigInteger ^ ValueBigInteger, B(operand ^ Value));
        Assert.IsTrue(Value > operand && operand < Value && Value != operand && operand != Value);
        Assert.AreEqual(Value << 7, Value << operand);
        Assert.AreEqual(Value >> 7, Value >> operand);
        Assert.AreEqual(Value >>> 7, Value >>> operand);
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue + operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.Zero - operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue * operand));
    }

    [TestMethod("U2048-INTEGRAL-S01: sbyte exact signed arithmetic bitwise comparison and shifts")]
    public void Signed_sbyte_Operators()
    {
        sbyte positive = (sbyte)7;
        sbyte negative = (sbyte)-7;
        var positiveBigInteger = new BigInteger(7);
        var negativeBigInteger = new BigInteger(-7);
        Assert.AreEqual(ValueBigInteger + positiveBigInteger, Value + positive);
        Assert.AreEqual(positiveBigInteger + ValueBigInteger, positive + Value);
        Assert.AreEqual(ValueBigInteger - positiveBigInteger, Value - positive);
        Assert.AreEqual(positiveBigInteger - ValueBigInteger, positive - Value);
        Assert.AreEqual(ValueBigInteger * negativeBigInteger, Value * negative);
        Assert.AreEqual(negativeBigInteger * ValueBigInteger, negative * Value);
        Assert.AreEqual(ValueBigInteger / negativeBigInteger, Value / negative);
        Assert.AreEqual(negativeBigInteger / ValueBigInteger, negative / Value);
        Assert.AreEqual(ValueBigInteger % negativeBigInteger, Value % negative);
        Assert.AreEqual(negativeBigInteger % ValueBigInteger, negative % Value);
        Assert.AreEqual(ValueBigInteger & negativeBigInteger, Value & negative);
        Assert.AreEqual(negativeBigInteger & ValueBigInteger, negative & Value);
        Assert.AreEqual(ValueBigInteger | negativeBigInteger, Value | negative);
        Assert.AreEqual(negativeBigInteger | ValueBigInteger, negative | Value);
        Assert.AreEqual(ValueBigInteger ^ negativeBigInteger, Value ^ negative);
        Assert.AreEqual(negativeBigInteger ^ ValueBigInteger, negative ^ Value);
        Assert.IsTrue(Value > negative && negative < Value && Value != negative && negative != Value);
        Assert.AreEqual(Value << 7, Value << positive);
        Assert.AreEqual(Value >> 7, Value >> positive);
        Assert.AreEqual(Value >>> 7, Value >>> positive);
        Assert.AreEqual(Value >> 7, Value << negative);
    }

    [TestMethod("U2048-INTEGRAL-S02: short exact signed arithmetic bitwise comparison and shifts")]
    public void Signed_short_Operators()
    {
        short positive = (short)7;
        short negative = (short)-7;
        var positiveBigInteger = new BigInteger(7);
        var negativeBigInteger = new BigInteger(-7);
        Assert.AreEqual(ValueBigInteger + positiveBigInteger, Value + positive);
        Assert.AreEqual(positiveBigInteger + ValueBigInteger, positive + Value);
        Assert.AreEqual(ValueBigInteger - positiveBigInteger, Value - positive);
        Assert.AreEqual(positiveBigInteger - ValueBigInteger, positive - Value);
        Assert.AreEqual(ValueBigInteger * negativeBigInteger, Value * negative);
        Assert.AreEqual(negativeBigInteger * ValueBigInteger, negative * Value);
        Assert.AreEqual(ValueBigInteger / negativeBigInteger, Value / negative);
        Assert.AreEqual(negativeBigInteger / ValueBigInteger, negative / Value);
        Assert.AreEqual(ValueBigInteger % negativeBigInteger, Value % negative);
        Assert.AreEqual(negativeBigInteger % ValueBigInteger, negative % Value);
        Assert.AreEqual(ValueBigInteger & negativeBigInteger, Value & negative);
        Assert.AreEqual(negativeBigInteger & ValueBigInteger, negative & Value);
        Assert.AreEqual(ValueBigInteger | negativeBigInteger, Value | negative);
        Assert.AreEqual(negativeBigInteger | ValueBigInteger, negative | Value);
        Assert.AreEqual(ValueBigInteger ^ negativeBigInteger, Value ^ negative);
        Assert.AreEqual(negativeBigInteger ^ ValueBigInteger, negative ^ Value);
        Assert.IsTrue(Value > negative && negative < Value && Value != negative && negative != Value);
        Assert.AreEqual(Value << 7, Value << positive);
        Assert.AreEqual(Value >> 7, Value >> positive);
        Assert.AreEqual(Value >>> 7, Value >>> positive);
        Assert.AreEqual(Value >> 7, Value << negative);
    }

    [TestMethod("U2048-INTEGRAL-S03: int exact signed arithmetic bitwise comparison and shifts")]
    public void Signed_int_Operators()
    {
        int positive = 7;
        int negative = -7;
        var positiveBigInteger = new BigInteger(7);
        var negativeBigInteger = new BigInteger(-7);
        Assert.AreEqual(ValueBigInteger + positiveBigInteger, Value + positive);
        Assert.AreEqual(positiveBigInteger + ValueBigInteger, positive + Value);
        Assert.AreEqual(ValueBigInteger - positiveBigInteger, Value - positive);
        Assert.AreEqual(positiveBigInteger - ValueBigInteger, positive - Value);
        Assert.AreEqual(ValueBigInteger * negativeBigInteger, Value * negative);
        Assert.AreEqual(negativeBigInteger * ValueBigInteger, negative * Value);
        Assert.AreEqual(ValueBigInteger / negativeBigInteger, Value / negative);
        Assert.AreEqual(negativeBigInteger / ValueBigInteger, negative / Value);
        Assert.AreEqual(ValueBigInteger % negativeBigInteger, Value % negative);
        Assert.AreEqual(negativeBigInteger % ValueBigInteger, negative % Value);
        Assert.AreEqual(ValueBigInteger & negativeBigInteger, Value & negative);
        Assert.AreEqual(negativeBigInteger & ValueBigInteger, negative & Value);
        Assert.AreEqual(ValueBigInteger | negativeBigInteger, Value | negative);
        Assert.AreEqual(negativeBigInteger | ValueBigInteger, negative | Value);
        Assert.AreEqual(ValueBigInteger ^ negativeBigInteger, Value ^ negative);
        Assert.AreEqual(negativeBigInteger ^ ValueBigInteger, negative ^ Value);
        Assert.IsTrue(Value > negative && negative < Value && Value != negative && negative != Value);
        Assert.AreEqual(Value << 7, Value << positive);
        Assert.AreEqual(Value >> 7, Value >> positive);
        Assert.AreEqual(Value >>> 7, Value >>> positive);
        Assert.AreEqual(Value >> 7, Value << negative);
    }

    [TestMethod("U2048-INTEGRAL-S04: long exact signed arithmetic bitwise comparison and shifts")]
    public void Signed_long_Operators()
    {
        long positive = 7L;
        long negative = -7L;
        var positiveBigInteger = new BigInteger(7);
        var negativeBigInteger = new BigInteger(-7);
        Assert.AreEqual(ValueBigInteger + positiveBigInteger, Value + positive);
        Assert.AreEqual(positiveBigInteger + ValueBigInteger, positive + Value);
        Assert.AreEqual(ValueBigInteger - positiveBigInteger, Value - positive);
        Assert.AreEqual(positiveBigInteger - ValueBigInteger, positive - Value);
        Assert.AreEqual(ValueBigInteger * negativeBigInteger, Value * negative);
        Assert.AreEqual(negativeBigInteger * ValueBigInteger, negative * Value);
        Assert.AreEqual(ValueBigInteger / negativeBigInteger, Value / negative);
        Assert.AreEqual(negativeBigInteger / ValueBigInteger, negative / Value);
        Assert.AreEqual(ValueBigInteger % negativeBigInteger, Value % negative);
        Assert.AreEqual(negativeBigInteger % ValueBigInteger, negative % Value);
        Assert.AreEqual(ValueBigInteger & negativeBigInteger, Value & negative);
        Assert.AreEqual(negativeBigInteger & ValueBigInteger, negative & Value);
        Assert.AreEqual(ValueBigInteger | negativeBigInteger, Value | negative);
        Assert.AreEqual(negativeBigInteger | ValueBigInteger, negative | Value);
        Assert.AreEqual(ValueBigInteger ^ negativeBigInteger, Value ^ negative);
        Assert.AreEqual(negativeBigInteger ^ ValueBigInteger, negative ^ Value);
        Assert.IsTrue(Value > negative && negative < Value && Value != negative && negative != Value);
        Assert.AreEqual(Value << 7, Value << positive);
        Assert.AreEqual(Value >> 7, Value >> positive);
        Assert.AreEqual(Value >>> 7, Value >>> positive);
        Assert.AreEqual(Value >> 7, Value << negative);
    }

    [TestMethod("U2048-INTEGRAL-S05: nint exact signed arithmetic bitwise comparison and shifts")]
    public void Signed_nint_Operators()
    {
        nint positive = (nint)(7);
        nint negative = (nint)(-7);
        var positiveBigInteger = new BigInteger(7);
        var negativeBigInteger = new BigInteger(-7);
        Assert.AreEqual(ValueBigInteger + positiveBigInteger, Value + positive);
        Assert.AreEqual(positiveBigInteger + ValueBigInteger, positive + Value);
        Assert.AreEqual(ValueBigInteger - positiveBigInteger, Value - positive);
        Assert.AreEqual(positiveBigInteger - ValueBigInteger, positive - Value);
        Assert.AreEqual(ValueBigInteger * negativeBigInteger, Value * negative);
        Assert.AreEqual(negativeBigInteger * ValueBigInteger, negative * Value);
        Assert.AreEqual(ValueBigInteger / negativeBigInteger, Value / negative);
        Assert.AreEqual(negativeBigInteger / ValueBigInteger, negative / Value);
        Assert.AreEqual(ValueBigInteger % negativeBigInteger, Value % negative);
        Assert.AreEqual(negativeBigInteger % ValueBigInteger, negative % Value);
        Assert.AreEqual(ValueBigInteger & negativeBigInteger, Value & negative);
        Assert.AreEqual(negativeBigInteger & ValueBigInteger, negative & Value);
        Assert.AreEqual(ValueBigInteger | negativeBigInteger, Value | negative);
        Assert.AreEqual(negativeBigInteger | ValueBigInteger, negative | Value);
        Assert.AreEqual(ValueBigInteger ^ negativeBigInteger, Value ^ negative);
        Assert.AreEqual(negativeBigInteger ^ ValueBigInteger, negative ^ Value);
        Assert.IsTrue(Value > negative && negative < Value && Value != negative && negative != Value);
        Assert.AreEqual(Value << 7, Value << positive);
        Assert.AreEqual(Value >> 7, Value >> positive);
        Assert.AreEqual(Value >>> 7, Value >>> positive);
        Assert.AreEqual(Value >> 7, Value << negative);
    }

    [TestMethod("U2048-INTEGRAL-S06: Int128 exact signed arithmetic bitwise comparison and shifts")]
    public void Signed_Int128_Operators()
    {
        Int128 positive = (Int128)(7);
        Int128 negative = (Int128)(-7);
        var positiveBigInteger = new BigInteger(7);
        var negativeBigInteger = new BigInteger(-7);
        Assert.AreEqual(ValueBigInteger + positiveBigInteger, Value + positive);
        Assert.AreEqual(positiveBigInteger + ValueBigInteger, positive + Value);
        Assert.AreEqual(ValueBigInteger - positiveBigInteger, Value - positive);
        Assert.AreEqual(positiveBigInteger - ValueBigInteger, positive - Value);
        Assert.AreEqual(ValueBigInteger * negativeBigInteger, Value * negative);
        Assert.AreEqual(negativeBigInteger * ValueBigInteger, negative * Value);
        Assert.AreEqual(ValueBigInteger / negativeBigInteger, Value / negative);
        Assert.AreEqual(negativeBigInteger / ValueBigInteger, negative / Value);
        Assert.AreEqual(ValueBigInteger % negativeBigInteger, Value % negative);
        Assert.AreEqual(negativeBigInteger % ValueBigInteger, negative % Value);
        Assert.AreEqual(ValueBigInteger & negativeBigInteger, Value & negative);
        Assert.AreEqual(negativeBigInteger & ValueBigInteger, negative & Value);
        Assert.AreEqual(ValueBigInteger | negativeBigInteger, Value | negative);
        Assert.AreEqual(negativeBigInteger | ValueBigInteger, negative | Value);
        Assert.AreEqual(ValueBigInteger ^ negativeBigInteger, Value ^ negative);
        Assert.AreEqual(negativeBigInteger ^ ValueBigInteger, negative ^ Value);
        Assert.IsTrue(Value > negative && negative < Value && Value != negative && negative != Value);
        Assert.AreEqual(Value << 7, Value << positive);
        Assert.AreEqual(Value >> 7, Value >> positive);
        Assert.AreEqual(Value >>> 7, Value >>> positive);
        Assert.AreEqual(Value >> 7, Value << negative);
    }

}
