// <auto-generated />
// Generated by scripts/generate_mstest_regression_adapter.py from
// RicisRegressionTestCatalog. Do not edit this file manually.
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Ricis.Core.UnitTests;

[TestClass]
public sealed class RicisRegressionCatalogMSTestAdapter
{
    [TestMethod("AX01: L0 — pipeline сохраняет payload и certified key indexed zero")]
    [TestCategory("Regression")]
    public void Regression_001() => RicisRegressionTestCatalog.Tests[0].Body();

    [TestMethod("AX02: SP1 — локальное сокращение сохраняет несокращённый хвост")]
    [TestCategory("Regression")]
    public void Regression_002() => RicisRegressionTestCatalog.Tests[1].Body();

    [TestMethod("AX03: SP3 — 0_F/0_G раскрывается в F/G без числового коллапса")]
    [TestCategory("Regression")]
    public void Regression_003() => RicisRegressionTestCatalog.Tests[2].Body();

    [TestMethod("AX04: SP4 — ноль singularity индексируется исходным выражением, а не числом")]
    [TestCategory("Regression")]
    public void Regression_004() => RicisRegressionTestCatalog.Tests[3].Body();

    [TestMethod("AX05: FractalLaw — ∞_F раскрывается в 0_F без утраты F и ключа")]
    [TestCategory("Regression")]
    public void Regression_005() => RicisRegressionTestCatalog.Tests[4].Body();

    [TestMethod("AX06: A6 — 0_F·∞_F возвращает структурное F²")]
    [TestCategory("Regression")]
    public void Regression_006() => RicisRegressionTestCatalog.Tests[5].Body();

    [TestMethod("AX07: A6 — (F·0)·(1/F) распознаётся как 0_F·∞_F и возвращает F²")]
    [TestCategory("Regression")]
    public void Regression_007() => RicisRegressionTestCatalog.Tests[6].Body();

    [TestMethod("PREV01: равные ответы F(x)=F(x−1) дают (F(x)/F(x−1))-1 = 0")]
    [TestCategory("Regression")]
    public void Regression_008() => RicisRegressionTestCatalog.Tests[7].Body();

    [TestMethod("PREV02: нулевые ответы проходят через RICIS 0_F/0_F = 1 и дают 0")]
    [TestCategory("Regression")]
    public void Regression_009() => RicisRegressionTestCatalog.Tests[8].Body();

    [TestMethod("PREV03: разные ответы F(x) и F(x−1) не принимаются как тождественные")]
    [TestCategory("Regression")]
    public void Regression_010() => RicisRegressionTestCatalog.Tests[9].Body();

    [TestMethod("SP4: коммутативно эквивалентные суммы имеют одну идентичность")]
    [TestCategory("Regression")]
    public void Regression_011() => RicisRegressionTestCatalog.Tests[10].Body();

    [TestMethod("SP2: (x + 1) / (1 + x) сокращается до 1")]
    [TestCategory("Regression")]
    public void Regression_012() => RicisRegressionTestCatalog.Tests[11].Body();

    [TestMethod("A5: одинаковые индексированные бесконечности при делении дают 1")]
    [TestCategory("Regression")]
    public void Regression_013() => RicisRegressionTestCatalog.Tests[12].Body();

    [TestMethod("SP4: индексированный ноль сохраняет отложенное F")]
    [TestCategory("Regression")]
    public void Regression_014() => RicisRegressionTestCatalog.Tests[13].Body();

    [TestMethod("A6: 0_F × ∞_G возвращает F·G")]
    [TestCategory("Regression")]
    public void Regression_015() => RicisRegressionTestCatalog.Tests[14].Body();

    [TestMethod("Полярная фаза точно сворачивает постоянную тригонометрию")]
    [TestCategory("Regression")]
    public void Regression_016() => RicisRegressionTestCatalog.Tests[15].Body();

    [TestMethod("Полярная фаза сохраняет символическую тригонометрию отложенной")]
    [TestCategory("Regression")]
    public void Regression_017() => RicisRegressionTestCatalog.Tests[16].Body();

    [TestMethod("Операции не смешивают сингулярности с разными наборами корней")]
    [TestCategory("Regression")]
    public void Regression_018() => RicisRegressionTestCatalog.Tests[17].Body();

    [TestMethod("Полиномиальный решатель: x = 0 даёт корень x = 0")]
    [TestCategory("Regression")]
    public void Regression_019() => RicisRegressionTestCatalog.Tests[18].Body();

    [TestMethod("Решатель экспоненты: exp(x) = 1 даёт корень x = 0")]
    [TestCategory("Regression")]
    public void Regression_020() => RicisRegressionTestCatalog.Tests[19].Body();

    [TestMethod("Решатель экспоненты: выражение без exp не выбрасывает исключение")]
    [TestCategory("Regression")]
    public void Regression_021() => RicisRegressionTestCatalog.Tests[20].Body();

    [TestMethod("Решатель логарифма: log(x + 1) даёт корень x = 0")]
    [TestCategory("Regression")]
    public void Regression_022() => RicisRegressionTestCatalog.Tests[21].Body();

    [TestMethod("Упрощатель не переставляет основание и показатель степени")]
    [TestCategory("Regression")]
    public void Regression_023() => RicisRegressionTestCatalog.Tests[22].Body();

    [TestMethod("Упрощатель не склеивает разные составные слагаемые")]
    [TestCategory("Regression")]
    public void Regression_024() => RicisRegressionTestCatalog.Tests[23].Body();

    [TestMethod("Упрощатель сохраняет дробный коэффициент")]
    [TestCategory("Regression")]
    public void Regression_025() => RicisRegressionTestCatalog.Tests[24].Body();

    [TestMethod("Упрощатель точно сворачивает вещественные константы")]
    [TestCategory("Regression")]
    public void Regression_026() => RicisRegressionTestCatalog.Tests[25].Body();

    [TestMethod("Упрощатель корректно преобразует x + x")]
    [TestCategory("Regression")]
    public void Regression_027() => RicisRegressionTestCatalog.Tests[26].Body();

    [TestMethod("Рациональная арифметика сохраняет каноническую форму")]
    [TestCategory("Regression")]
    public void Regression_028() => RicisRegressionTestCatalog.Tests[27].Body();

    [TestMethod("Generic INumber: BigInteger сохраняется в SP2 и конечном делегате")]
    [TestCategory("Regression")]
    public void Regression_029() => RicisRegressionTestCatalog.Tests[28].Body();

    [TestMethod("Generic INumber: X/X возвращает типизированную единицу")]
    [TestCategory("Regression")]
    public void Regression_030() => RicisRegressionTestCatalog.Tests[29].Body();

    [TestMethod("S01: 10/(x-2) сохраняет индекс F и ключ корня")]
    [TestCategory("Regression")]
    public void Regression_031() => RicisRegressionTestCatalog.Tests[30].Body();

    [TestMethod("S02: SP2 сокращает (x²-25)/(x-5) до отложенного хвоста")]
    [TestCategory("Regression")]
    public void Regression_032() => RicisRegressionTestCatalog.Tests[31].Body();

    [TestMethod("S03: 1/(2x-6) создаёт индексированную бесконечность")]
    [TestCategory("Regression")]
    public void Regression_033() => RicisRegressionTestCatalog.Tests[32].Body();

    [TestMethod("S04: 1/(x²-4) сохраняет все корни")]
    [TestCategory("Regression")]
    public void Regression_034() => RicisRegressionTestCatalog.Tests[33].Body();

    [TestMethod("S05: sin(x)/cos(x) даёт ∞₁ после подстановки ключа")]
    [TestCategory("Regression")]
    public void Regression_035() => RicisRegressionTestCatalog.Tests[34].Body();

    [TestMethod("S06: sin(x)/x остаётся отношением отложенных F/G")]
    [TestCategory("Regression")]
    public void Regression_036() => RicisRegressionTestCatalog.Tests[35].Body();

    [TestMethod("S07: sin(2x)/cos(2x) сохраняет ветви ∞₁ и ∞_{−1} по ключам")]
    [TestCategory("Regression")]
    public void Regression_037() => RicisRegressionTestCatalog.Tests[36].Body();

    [TestMethod("S08: SP2 раскрывает частное x⁴-1 над x-1")]
    [TestCategory("Regression")]
    public void Regression_038() => RicisRegressionTestCatalog.Tests[37].Body();

    [TestMethod("S09: 1/log(x) создаёт ∞_1 в корне логарифма")]
    [TestCategory("Regression")]
    public void Regression_039() => RicisRegressionTestCatalog.Tests[38].Body();

    [TestMethod("S10: (exp(x)-1)/x остаётся отложенным F/G")]
    [TestCategory("Regression")]
    public void Regression_040() => RicisRegressionTestCatalog.Tests[39].Body();

    [TestMethod("S11: (1-cos(x))/x² остаётся отложенным F/G")]
    [TestCategory("Regression")]
    public void Regression_041() => RicisRegressionTestCatalog.Tests[40].Body();

    [TestMethod("S12: tan(x)/x остаётся отложенным F/G")]
    [TestCategory("Regression")]
    public void Regression_042() => RicisRegressionTestCatalog.Tests[41].Body();

    [TestMethod("S13: 1/(x(x+1)) сохраняет оба полюса")]
    [TestCategory("Regression")]
    public void Regression_043() => RicisRegressionTestCatalog.Tests[42].Body();

    [TestMethod("S14: 1/(1-x²) сохраняет оба полюса")]
    [TestCategory("Regression")]
    public void Regression_044() => RicisRegressionTestCatalog.Tests[43].Body();

    [TestMethod("S15: exp(1/x) рекурсивно содержит ∞_1")]
    [TestCategory("Regression")]
    public void Regression_045() => RicisRegressionTestCatalog.Tests[44].Body();

    [TestMethod("S16: 1/x создаёт ∞_1")]
    [TestCategory("Regression")]
    public void Regression_046() => RicisRegressionTestCatalog.Tests[45].Body();

    [TestMethod("S17: 1/x² создаёт ∞_1")]
    [TestCategory("Regression")]
    public void Regression_047() => RicisRegressionTestCatalog.Tests[46].Body();

    [TestMethod("S18: log(x) возвращается без искусственного преобразования")]
    [TestCategory("Regression")]
    public void Regression_048() => RicisRegressionTestCatalog.Tests[47].Body();

    [TestMethod("S19: повтор S06 сохраняет тот же F/G")]
    [TestCategory("Regression")]
    public void Regression_049() => RicisRegressionTestCatalog.Tests[48].Body();

    [TestMethod("S20: повтор S15 сохраняет вложенную сингулярность")]
    [TestCategory("Regression")]
    public void Regression_050() => RicisRegressionTestCatalog.Tests[49].Body();

    [TestMethod("S21: повтор S16 сохраняет ∞_1")]
    [TestCategory("Regression")]
    public void Regression_051() => RicisRegressionTestCatalog.Tests[50].Body();

    [TestMethod("S22: 1/(1-x) создаёт ∞_1 при x=1")]
    [TestCategory("Regression")]
    public void Regression_052() => RicisRegressionTestCatalog.Tests[51].Body();

    [TestMethod("S23: повтор S22 сохраняет тот же полюс")]
    [TestCategory("Regression")]
    public void Regression_053() => RicisRegressionTestCatalog.Tests[52].Body();

    [TestMethod("S24: SP2 сокращает x/(x²), а A1 возвращает ∞₁")]
    [TestCategory("Regression")]
    public void Regression_054() => RicisRegressionTestCatalog.Tests[53].Body();

    [TestMethod("S25: SP2 сокращает 2x/x до 2")]
    [TestCategory("Regression")]
    public void Regression_055() => RicisRegressionTestCatalog.Tests[54].Body();

    [TestMethod("S26: 1/(x⁴-1) сохраняет действительные полюса")]
    [TestCategory("Regression")]
    public void Regression_056() => RicisRegressionTestCatalog.Tests[55].Body();

    [TestMethod("N01: (x/0)/(2/0) сокращает общий нулевой фактор до x/2")]
    [TestCategory("Regression")]
    public void Regression_057() => RicisRegressionTestCatalog.Tests[56].Body();

    [TestMethod("N02: (8/0)/(4/0) сокращает общий нулевой фактор до 2")]
    [TestCategory("Regression")]
    public void Regression_058() => RicisRegressionTestCatalog.Tests[57].Body();

    [TestMethod("N03: (1/0)/(2/0) сохраняет несократимую дробь 1/2")]
    [TestCategory("Regression")]
    public void Regression_059() => RicisRegressionTestCatalog.Tests[58].Body();

    [TestMethod("N04: одинаковые функции с теми же параметрами сокращаются по F/F")]
    [TestCategory("Regression")]
    public void Regression_060() => RicisRegressionTestCatalog.Tests[59].Body();

    [TestMethod("N05: одинаковые составные выражения сокращаются по F/F")]
    [TestCategory("Regression")]
    public void Regression_061() => RicisRegressionTestCatalog.Tests[60].Body();

    [TestMethod("N06: uint (a·a)/a сокращается до a до переполнения")]
    [TestCategory("Regression")]
    public void Regression_062() => RicisRegressionTestCatalog.Tests[61].Body();

    [TestMethod("N07: int.MaxValue (a·a)/a сокращается до a до переполнения")]
    [TestCategory("Regression")]
    public void Regression_063() => RicisRegressionTestCatalog.Tests[62].Body();

    [TestMethod("N08: 10!/9! сокращается до 10 до вычисления факториалов")]
    [TestCategory("Regression")]
    public void Regression_064() => RicisRegressionTestCatalog.Tests[63].Body();

    [TestMethod("N09: все 70 ассоциативных вариантов a⁵/a⁴ сокращаются до a")]
    [TestCategory("Regression")]
    public void Regression_065() => RicisRegressionTestCatalog.Tests[64].Body();

    [TestMethod("N10: пользовательские * и / строго наследуют классику")]
    [TestCategory("Regression")]
    public void Regression_066() => RicisRegressionTestCatalog.Tests[65].Body();

    [TestMethod("L01: F·0 возвращает индексированный ноль 0_F")]
    [TestCategory("Regression")]
    public void Regression_067() => RicisRegressionTestCatalog.Tests[66].Body();

    [TestMethod("L02: 0·F возвращает индексированный ноль 0_F")]
    [TestCategory("Regression")]
    public void Regression_068() => RicisRegressionTestCatalog.Tests[67].Body();

    [TestMethod("L03: F/0 возвращает индексированную бесконечность ∞_F")]
    [TestCategory("Regression")]
    public void Regression_069() => RicisRegressionTestCatalog.Tests[68].Body();

    [TestMethod("B01: O(1)-детектор заменяет F·0 мостом 0_F")]
    [TestCategory("Regression")]
    public void Regression_070() => RicisRegressionTestCatalog.Tests[69].Body();

    [TestMethod("B02: O(1)-детектор заменяет 0·F мостом 0_F")]
    [TestCategory("Regression")]
    public void Regression_071() => RicisRegressionTestCatalog.Tests[70].Body();

    [TestMethod("B03: O(1)-детектор заменяет F/0 мостом ∞_F")]
    [TestCategory("Regression")]
    public void Regression_072() => RicisRegressionTestCatalog.Tests[71].Body();

    [TestMethod("B04: O(1)-детектор не меняет не-предельную форму")]
    [TestCategory("Regression")]
    public void Regression_073() => RicisRegressionTestCatalog.Tests[72].Body();

    [TestMethod("B05: константный 0/0 возвращает 1 до A1")]
    [TestCategory("Regression")]
    public void Regression_074() => RicisRegressionTestCatalog.Tests[73].Body();

    [TestMethod("B06: ∞_C/∞_C возвращает 1 по A5")]
    [TestCategory("Regression")]
    public void Regression_075() => RicisRegressionTestCatalog.Tests[74].Body();

    [TestMethod("B07: тождество F/F предшествует полярной фазе")]
    [TestCategory("Regression")]
    public void Regression_076() => RicisRegressionTestCatalog.Tests[75].Body();

    [TestMethod("B08: тождество ∞/∞ предшествует A5")]
    [TestCategory("Regression")]
    public void Regression_077() => RicisRegressionTestCatalog.Tests[76].Body();

    [TestMethod("K01: (x²-9)/(x-3) — SP2 возвращает отложенное частное x+3")]
    [TestCategory("Regression")]
    public void Regression_078() => RicisRegressionTestCatalog.Tests[77].Body();

    [TestMethod("K02: (x³-8)/(x-2) — SP2 возвращает отложенное частное")]
    [TestCategory("Regression")]
    public void Regression_079() => RicisRegressionTestCatalog.Tests[78].Body();

    [TestMethod("K03: F/F — одинаковое выражение возвращает 1")]
    [TestCategory("Regression")]
    public void Regression_080() => RicisRegressionTestCatalog.Tests[79].Body();

    [TestMethod("K04: 1/(x-3) — полюс становится ∞₁ с ключом точки")]
    [TestCategory("Regression")]
    public void Regression_081() => RicisRegressionTestCatalog.Tests[80].Body();

    [TestMethod("K05: F·0 — мост предела возвращает 0_F")]
    [TestCategory("Regression")]
    public void Regression_082() => RicisRegressionTestCatalog.Tests[81].Body();

    [TestMethod("K06: F/0 — мост предела возвращает ∞_F")]
    [TestCategory("Regression")]
    public void Regression_083() => RicisRegressionTestCatalog.Tests[82].Body();

    [TestMethod("K07: (x/0)/(2/0) — SP2 выполняется до мостов")]
    [TestCategory("Regression")]
    public void Regression_084() => RicisRegressionTestCatalog.Tests[83].Body();

    [TestMethod("K08: sin(π/2) — полярная фаза возвращает 1")]
    [TestCategory("Regression")]
    public void Regression_085() => RicisRegressionTestCatalog.Tests[84].Body();

    [TestMethod("K09: tan(π/2) — полярная фаза возвращает ∞₁")]
    [TestCategory("Regression")]
    public void Regression_086() => RicisRegressionTestCatalog.Tests[85].Body();

    [TestMethod("K10: sin(x)/x — неизвестная форма остаётся отношением F/G")]
    [TestCategory("Regression")]
    public void Regression_087() => RicisRegressionTestCatalog.Tests[86].Body();

    [TestMethod("K11: 0_F·∞_G — A6 возвращает отложенное произведение F·G")]
    [TestCategory("Regression")]
    public void Regression_088() => RicisRegressionTestCatalog.Tests[87].Body();

    [TestMethod("K12: эталон с нулевым знаменателем падает, производное x/2 выполняется")]
    [TestCategory("Regression")]
    public void Regression_089() => RicisRegressionTestCatalog.Tests[88].Body();

    [TestMethod("C01: RICIS x+5 совпадает с классическим пределом 10")]
    [TestCategory("Regression")]
    public void Regression_090() => RicisRegressionTestCatalog.Tests[89].Body();

    [TestMethod("C02: RICIS кубическое частное совпадает с классическим пределом 12")]
    [TestCategory("Regression")]
    public void Regression_091() => RicisRegressionTestCatalog.Tests[90].Body();

    [TestMethod("C03: RICIS x/2 совпадает с классическим значением 2")]
    [TestCategory("Regression")]
    public void Regression_092() => RicisRegressionTestCatalog.Tests[91].Body();

    [TestMethod("C04: RICIS 2 совпадает с классическим пределом 2")]
    [TestCategory("Regression")]
    public void Regression_093() => RicisRegressionTestCatalog.Tests[92].Body();

    [TestMethod("C05: RICIS sin(π/2) совпадает с классическим значением 1")]
    [TestCategory("Regression")]
    public void Regression_094() => RicisRegressionTestCatalog.Tests[93].Body();

    [TestMethod("C06: классический NaN sin(x)/x остаётся отложенным F/G в RICIS")]
    [TestCategory("Regression")]
    public void Regression_095() => RicisRegressionTestCatalog.Tests[94].Body();

    [TestMethod("C07: классический +Infinity 1/x становится символическим ∞₁ в RICIS")]
    [TestCategory("Regression")]
    public void Regression_096() => RicisRegressionTestCatalog.Tests[95].Body();

    [TestMethod("C08: классический NaN x/x становится точной константой 1 в RICIS")]
    [TestCategory("Regression")]
    public void Regression_097() => RicisRegressionTestCatalog.Tests[96].Body();

    [TestMethod("C09: классический NaN (exp(x)-1)/x остаётся отложенным F/G в RICIS")]
    [TestCategory("Regression")]
    public void Regression_098() => RicisRegressionTestCatalog.Tests[97].Body();

    [TestMethod("D01: DxDt int — t·t строит 2·t")]
    [TestCategory("Regression")]
    public void Regression_099() => RicisRegressionTestCatalog.Tests[98].Body();

    [TestMethod("D02: Derivative decimal — правило частного остаётся типизированным")]
    [TestCategory("Regression")]
    public void Regression_100() => RicisRegressionTestCatalog.Tests[99].Body();

    [TestMethod("D03: DxDt BigInteger — куб строится без double")]
    [TestCategory("Regression")]
    public void Regression_101() => RicisRegressionTestCatalog.Tests[100].Body();

    [TestMethod("D04: DxDt — L1 нормализует t/t до константы перед производной")]
    [TestCategory("Regression")]
    public void Regression_102() => RicisRegressionTestCatalog.Tests[101].Body();

    [TestMethod("D05: Derivative — неизвестная функция остаётся D_t(F), а не 0")]
    [TestCategory("Regression")]
    public void Regression_103() => RicisRegressionTestCatalog.Tests[102].Body();

    [TestMethod("D06: Derivative — alias DxDt возвращает то же дерево")]
    [TestCategory("Regression")]
    public void Regression_104() => RicisRegressionTestCatalog.Tests[103].Body();

    [TestMethod("D07: DxDt double — Expression.Power с постоянной степенью")]
    [TestCategory("Regression")]
    public void Regression_105() => RicisRegressionTestCatalog.Tests[104].Body();

    [TestMethod("D08: DxDt double — цепное правило Math.Sin")]
    [TestCategory("Regression")]
    public void Regression_106() => RicisRegressionTestCatalog.Tests[105].Body();

    [TestMethod("D09: DxDt double — Math.Pow с постоянной степенью")]
    [TestCategory("Regression")]
    public void Regression_107() => RicisRegressionTestCatalog.Tests[106].Body();

    [TestMethod("D10: DxDt — t³ совпадает с классическим 3t²")]
    [TestCategory("Regression")]
    public void Regression_108() => RicisRegressionTestCatalog.Tests[107].Body();

    [TestMethod("D11: DxDt — sin(t²)+t³ совпадает с классическим цепным правилом")]
    [TestCategory("Regression")]
    public void Regression_109() => RicisRegressionTestCatalog.Tests[108].Body();

    [TestMethod("D12: DxDt — t²·sin(t) совпадает с классическим правилом произведения")]
    [TestCategory("Regression")]
    public void Regression_110() => RicisRegressionTestCatalog.Tests[109].Body();

    [TestMethod("I01: Integral — F и постоянная ширина дают F·L")]
    [TestCategory("Regression")]
    public void Regression_111() => RicisRegressionTestCatalog.Tests[110].Body();

    [TestMethod("I02: Integral — отложенная ширина связывается с параметром F")]
    [TestCategory("Regression")]
    public void Regression_112() => RicisRegressionTestCatalog.Tests[111].Body();

    [TestMethod("I03: Integral — L1 нормализует F до геометрического A6")]
    [TestCategory("Regression")]
    public void Regression_113() => RicisRegressionTestCatalog.Tests[112].Body();

    [TestMethod("I04: Integral — BigInteger не приводится к double")]
    [TestCategory("Regression")]
    public void Regression_114() => RicisRegressionTestCatalog.Tests[113].Body();

    [TestMethod("I05: Integral — результат совпадает с нормативным A6 F·G")]
    [TestCategory("Regression")]
    public void Regression_115() => RicisRegressionTestCatalog.Tests[114].Body();

    [TestMethod("SUM01: Sum — F и G связываются в независимое F+G")]
    [TestCategory("Regression")]
    public void Regression_116() => RicisRegressionTestCatalog.Tests[115].Body();

    [TestMethod("SUM02: Sum — L1 нормализует слагаемое до сложения")]
    [TestCategory("Regression")]
    public void Regression_117() => RicisRegressionTestCatalog.Tests[116].Body();

    [TestMethod("SUM03: Sum — BigInteger не приводится к double")]
    [TestCategory("Regression")]
    public void Regression_118() => RicisRegressionTestCatalog.Tests[117].Body();

    [TestMethod("PROOF01: Compose — подстановка строит F∘G без вызова делегата")]
    [TestCategory("Regression")]
    public void Regression_119() => RicisRegressionTestCatalog.Tests[118].Body();

    [TestMethod("PROOF02: At — является точным alias структурной подстановки")]
    [TestCategory("Regression")]
    public void Regression_120() => RicisRegressionTestCatalog.Tests[119].Body();

    [TestMethod("PROOF03: Difference — одинаковые нормализованные F и G дают типизированный 0")]
    [TestCategory("Regression")]
    public void Regression_121() => RicisRegressionTestCatalog.Tests[120].Body();

    [TestMethod("PROOF04: Ratio — L1 упрощает F/G до 1 до вычисления")]
    [TestCategory("Regression")]
    public void Regression_122() => RicisRegressionTestCatalog.Tests[121].Body();

    [TestMethod("PROOF05: Product — сохраняет generic BigInteger без double")]
    [TestCategory("Regression")]
    public void Regression_123() => RicisRegressionTestCatalog.Tests[122].Body();

    [TestMethod("PROOF06: Compose — L1 применяется к внешней функции до подстановки")]
    [TestCategory("Regression")]
    public void Regression_124() => RicisRegressionTestCatalog.Tests[123].Body();

    [TestMethod("PROVE01: Prove — SP2 выводит производное выражение и академический протокол")]
    [TestCategory("Regression")]
    public void Regression_125() => RicisRegressionTestCatalog.Tests[124].Body();

    [TestMethod("PROVE02: Prove — условия и ограничения не исполняются")]
    [TestCategory("Regression")]
    public void Regression_126() => RicisRegressionTestCatalog.Tests[125].Body();

    [TestMethod("PROVE03: Prove — generic BigInteger сохраняет тип и отмечает пропуск A1/A4")]
    [TestCategory("Regression")]
    public void Regression_127() => RicisRegressionTestCatalog.Tests[126].Body();

    [TestMethod("PROVE04: Prove — StringBuilder дописывается без потери существующего текста")]
    [TestCategory("Regression")]
    public void Regression_128() => RicisRegressionTestCatalog.Tests[127].Body();

    [TestMethod("PROVE05: Trace — конвейер публикует все нормативные фазы")]
    [TestCategory("Regression")]
    public void Regression_129() => RicisRegressionTestCatalog.Tests[128].Body();

    [TestMethod("PROVE06: Prove — разность кубов выводит x²+2x+4 при x≠2")]
    [TestCategory("Regression")]
    public void Regression_130() => RicisRegressionTestCatalog.Tests[129].Body();

    [TestMethod("PROVE07: Prove — печатает полный node-to-root RICIS pipeline")]
    [TestCategory("Regression")]
    public void Regression_131() => RicisRegressionTestCatalog.Tests[130].Body();

    [TestMethod("PROVE08: Prove — раскрывает сокращение общего множителя как промежуточный шаг")]
    [TestCategory("Regression")]
    public void Regression_132() => RicisRegressionTestCatalog.Tests[131].Body();

    [TestMethod("PROVE09: Prove — система x+y=5, x−y=1 выводит x=3")]
    [TestCategory("Regression")]
    public void Regression_133() => RicisRegressionTestCatalog.Tests[132].Body();

    [TestMethod("PROVE10: Prove — система отклоняет противоречащий тезис")]
    [TestCategory("Regression")]
    public void Regression_134() => RicisRegressionTestCatalog.Tests[133].Body();

    [TestMethod("PROVE11: Prove — разность квадратов с A+B раскрывает промежуточные шаги")]
    [TestCategory("Regression")]
    public void Regression_135() => RicisRegressionTestCatalog.Tests[134].Body();

    [TestMethod("PROVE12: Prove — сумма кубов раскрывает промежуточные шаги")]
    [TestCategory("Regression")]
    public void Regression_136() => RicisRegressionTestCatalog.Tests[135].Body();

    [TestMethod("PROVE13: Prove — вложенная дробь показывает очищение знаменателя")]
    [TestCategory("Regression")]
    public void Regression_137() => RicisRegressionTestCatalog.Tests[136].Body();

    [TestMethod("PROVE14: Prove — ассоциативное сокращение фиксируется в протоколе")]
    [TestCategory("Regression")]
    public void Regression_138() => RicisRegressionTestCatalog.Tests[137].Body();

    [TestMethod("PROVE15: Prove — n!/(n−BigInteger.One)! сокращается структурно")]
    [TestCategory("Regression")]
    public void Regression_139() => RicisRegressionTestCatalog.Tests[138].Body();

    [TestMethod("PROVE16: Prove — система отклоняет не-конечные и переполняющиеся double-выводы")]
    [TestCategory("Regression")]
    public void Regression_140() => RicisRegressionTestCatalog.Tests[139].Body();

    [TestMethod("PROVE17: ProveDocument — generic вывод публикует условный статус и границы")]
    [TestCategory("Regression")]
    public void Regression_141() => RicisRegressionTestCatalog.Tests[140].Body();

    [TestMethod("RIEMANN01: ID-01–ID-06 выводят σ=1/2 как точную дробь")]
    [TestCategory("Regression")]
    public void Regression_142() => RicisRegressionTestCatalog.Tests[141].Body();

    [TestMethod("RIEMANN02: ID-цепочка отвергает ложное следствие")]
    [TestCategory("Regression")]
    public void Regression_143() => RicisRegressionTestCatalog.Tests[142].Body();

    [TestMethod("RIEMANN03: ID-цепочка сохраняет однопроходные ограничения")]
    [TestCategory("Regression")]
    public void Regression_144() => RicisRegressionTestCatalog.Tests[143].Body();

    [TestMethod("RIEMANN04: специализированный case отделяет аналитику от RICIS-алгебры")]
    [TestCategory("Regression")]
    public void Regression_145() => RicisRegressionTestCatalog.Tests[144].Body();

    [TestMethod("NS01: частная производная строится точным expression tree")]
    [TestCategory("Regression")]
    public void Regression_146() => RicisRegressionTestCatalog.Tests[145].Body();

    [TestMethod("NS02: градиент, дивергенция и лапласиан покрывают типовые операторы поля")]
    [TestCategory("Regression")]
    public void Regression_147() => RicisRegressionTestCatalog.Tests[146].Body();

    [TestMethod("NS03: стационарный вихрь имеет нулевой остаток Навье—Стокса")]
    [TestCategory("Regression")]
    public void Regression_148() => RicisRegressionTestCatalog.Tests[147].Body();

    [TestMethod("NS04: proof отвергает сжимаемое поле")]
    [TestCategory("Regression")]
    public void Regression_149() => RicisRegressionTestCatalog.Tests[148].Body();

    [TestMethod("NS05: proof отвергает невалидную вязкость")]
    [TestCategory("Regression")]
    public void Regression_150() => RicisRegressionTestCatalog.Tests[149].Body();

    [TestMethod("NS06: стационарная производная канонизирует -0 в 0")]
    [TestCategory("Regression")]
    public void Regression_151() => RicisRegressionTestCatalog.Tests[150].Body();

    [TestMethod("NS07: производная F·0 сохраняет индексированный ноль 0_F")]
    [TestCategory("Regression")]
    public void Regression_152() => RicisRegressionTestCatalog.Tests[151].Body();

    [TestMethod("NS08: конечное F/∞_G даёт индексированный ноль 0_F")]
    [TestCategory("Regression")]
    public void Regression_153() => RicisRegressionTestCatalog.Tests[152].Body();

    [TestMethod("SUGAR01: Abs — строит конечное условное дерево |F|")]
    [TestCategory("Regression")]
    public void Regression_154() => RicisRegressionTestCatalog.Tests[153].Body();

    [TestMethod("SUGAR02: Abs — одинаковые |F| сохраняют L1 в отношении")]
    [TestCategory("Regression")]
    public void Regression_155() => RicisRegressionTestCatalog.Tests[154].Body();

    [TestMethod("SUGAR03: Min/Max — связывают разные параметры без вычисления")]
    [TestCategory("Regression")]
    public void Regression_156() => RicisRegressionTestCatalog.Tests[155].Body();

    [TestMethod("SUGAR04: Max — одинаковые нормализованные функции дают F")]
    [TestCategory("Regression")]
    public void Regression_157() => RicisRegressionTestCatalog.Tests[156].Body();

    [TestMethod("SUGAR05: Clamp — постоянные границы задают min(max(F,L),U)")]
    [TestCategory("Regression")]
    public void Regression_158() => RicisRegressionTestCatalog.Tests[157].Body();

    [TestMethod("SUGAR06: Clamp — отложенные границы остаются expression tree")]
    [TestCategory("Regression")]
    public void Regression_159() => RicisRegressionTestCatalog.Tests[158].Body();

    [TestMethod("SUGAR07: Положительная и отрицательная части сохраняют BigInteger")]
    [TestCategory("Regression")]
    public void Regression_160() => RicisRegressionTestCatalog.Tests[159].Body();

    [TestMethod("SUGAR08: Distance — строит |F−G| из независимых лямбд")]
    [TestCategory("Regression")]
    public void Regression_161() => RicisRegressionTestCatalog.Tests[160].Body();

    [TestMethod("CPLX01: AsComplex — вещественная функция получает нулевую Im-компоненту")]
    [TestCategory("Regression")]
    public void Regression_162() => RicisRegressionTestCatalog.Tests[161].Body();

    [TestMethod("CPLX02: AsComplex — Re и Im связываются с одним параметром")]
    [TestCategory("Regression")]
    public void Regression_163() => RicisRegressionTestCatalog.Tests[162].Body();

    [TestMethod("CPLX03: Conjugate — меняет знак Im без вычисления Re")]
    [TestCategory("Regression")]
    public void Regression_164() => RicisRegressionTestCatalog.Tests[163].Body();

    [TestMethod("CPLX04: Add/Subtract — сохраняют покомпонентную комплексную алгебру")]
    [TestCategory("Regression")]
    public void Regression_165() => RicisRegressionTestCatalog.Tests[164].Body();

    [TestMethod("CPLX05: Multiply — реализует (ac−bd)+i(ad+bc)")]
    [TestCategory("Regression")]
    public void Regression_166() => RicisRegressionTestCatalog.Tests[165].Body();

    [TestMethod("CPLX06: SquaredNorm — сохраняет точность BigInteger")]
    [TestCategory("Regression")]
    public void Regression_167() => RicisRegressionTestCatalog.Tests[166].Body();

    [TestMethod("CPLX07: Norm — строит sqrt(Re²+Im²) как дерево Math.Sqrt")]
    [TestCategory("Regression")]
    public void Regression_168() => RicisRegressionTestCatalog.Tests[167].Body();

    [TestMethod("API01: ExactEvaluator вычисляет рациональное expression")]
    [TestCategory("Regression")]
    public void Regression_169() => RicisRegressionTestCatalog.Tests[168].Body();

    [TestMethod("API02: ExactEvaluator отклоняет неподдерживаемый узел и неизвестный параметр")]
    [TestCategory("Regression")]
    public void Regression_170() => RicisRegressionTestCatalog.Tests[169].Body();

    [TestMethod("API03: CircleSectors нормализует радианную четверть и форматирует сектора")]
    [TestCategory("Regression")]
    public void Regression_171() => RicisRegressionTestCatalog.Tests[170].Body();

    [TestMethod("API04: CircleSectors отклоняет NaN, infinity и неверное число секторов")]
    [TestCategory("Regression")]
    public void Regression_172() => RicisRegressionTestCatalog.Tests[171].Body();

    [TestMethod("API05: PolarConverter возвращает exact sin/cos и оставляет неизвестный сектор")]
    [TestCategory("Regression")]
    public void Regression_173() => RicisRegressionTestCatalog.Tests[172].Body();

    [TestMethod("API06: PolarConverter сворачивает sin и pole tan через public API")]
    [TestCategory("Regression")]
    public void Regression_174() => RicisRegressionTestCatalog.Tests[173].Body();

    [TestMethod("API07: NumericConstants возвращает typed identities и predicates")]
    [TestCategory("Regression")]
    public void Regression_175() => RicisRegressionTestCatalog.Tests[174].Body();

    [TestMethod("API08: NumericConstants отклоняет незарегистрированный тип")]
    [TestCategory("Regression")]
    public void Regression_176() => RicisRegressionTestCatalog.Tests[175].Body();

    [TestMethod("API09: RicisType сохраняет equality/hash contract и compatibility")]
    [TestCategory("Regression")]
    public void Regression_177() => RicisRegressionTestCatalog.Tests[176].Body();

    [TestMethod("API10: RicisType строит canonical operations and tuple")]
    [TestCategory("Regression")]
    public void Regression_178() => RicisRegressionTestCatalog.Tests[177].Body();

    [TestMethod("API11: GetHashCode не меняет expression tree и HashSet semantics")]
    [TestCategory("Regression")]
    public void Regression_179() => RicisRegressionTestCatalog.Tests[178].Body();

    [TestMethod("API12: RicisType constructor, properties and constants are stable")]
    [TestCategory("Regression")]
    public void Regression_180() => RicisRegressionTestCatalog.Tests[179].Body();

    [TestMethod("API13: RicisType equality handles null and unrelated objects")]
    [TestCategory("Regression")]
    public void Regression_181() => RicisRegressionTestCatalog.Tests[180].Body();

    [TestMethod("API14: RicisType compatibility matrix is complete")]
    [TestCategory("Regression")]
    public void Regression_182() => RicisRegressionTestCatalog.Tests[181].Body();

    [TestMethod("API15: RicisType Operate covers scalar, identity and composite branches")]
    [TestCategory("Regression")]
    public void Regression_183() => RicisRegressionTestCatalog.Tests[182].Body();

    [TestMethod("API16: RicisType tuple and string representations are canonical")]
    [TestCategory("Regression")]
    public void Regression_184() => RicisRegressionTestCatalog.Tests[183].Body();

    [TestMethod("API19: Expression extensions evaluate finite scalar contracts")]
    [TestCategory("Regression")]
    public void Regression_185() => RicisRegressionTestCatalog.Tests[184].Body();

    [TestMethod("API20: Expression extensions expose ordering and parameter discovery")]
    [TestCategory("Regression")]
    public void Regression_186() => RicisRegressionTestCatalog.Tests[185].Body();

    [TestMethod("API21: Expression extensions classify transcendental shape and BigInteger conversion")]
    [TestCategory("Regression")]
    public void Regression_187() => RicisRegressionTestCatalog.Tests[186].Body();

    [TestMethod("API26: PolarConverter.ToPolarSector renders public singularity view")]
    [TestCategory("Regression")]
    public void Regression_188() => RicisRegressionTestCatalog.Tests[187].Body();

    [TestMethod("API27: Polynomial FindRootsInRange returns bounded approximate roots")]
    [TestCategory("Regression")]
    public void Regression_189() => RicisRegressionTestCatalog.Tests[188].Body();

    [TestMethod("API28: ExponentialZeroSolver public adapter returns exact and unsupported outcomes")]
    [TestCategory("Regression")]
    public void Regression_190() => RicisRegressionTestCatalog.Tests[189].Body();

    [TestMethod("API29: LogSolver public adapter returns exact and unsupported outcomes")]
    [TestCategory("Regression")]
    public void Regression_191() => RicisRegressionTestCatalog.Tests[190].Body();

    [TestMethod("API30: AlgebraicSimplifier facade preserves safe arithmetic reduction")]
    [TestCategory("Regression")]
    public void Regression_192() => RicisRegressionTestCatalog.Tests[191].Body();

    [TestMethod("API31: RicisTransformPhase facade preserves ordinary expression")]
    [TestCategory("Regression")]
    public void Regression_193() => RicisRegressionTestCatalog.Tests[192].Body();

    [TestMethod("API32: LogicalSimplifier exposes safe public Boolean reduction")]
    [TestCategory("Regression")]
    public void Regression_194() => RicisRegressionTestCatalog.Tests[193].Body();

    [TestMethod("INT01: CompoundInterest — decimal вычисляет S·(1+r/100)^n точно")]
    [TestCategory("Regression")]
    public void Regression_195() => RicisRegressionTestCatalog.Tests[194].Body();

    [TestMethod("INT02: CompoundInterest — связывает отложенные S и r")]
    [TestCategory("Regression")]
    public void Regression_196() => RicisRegressionTestCatalog.Tests[195].Body();

    [TestMethod("INT03: CompoundInterest — n=0 возвращает нормализованный S")]
    [TestCategory("Regression")]
    public void Regression_197() => RicisRegressionTestCatalog.Tests[196].Body();

    [TestMethod("INT04: CompoundInterest — BigInteger сохраняет native-точность")]
    [TestCategory("Regression")]
    public void Regression_198() => RicisRegressionTestCatalog.Tests[197].Body();

    [TestMethod("INT05: CompoundInterest — double-период сохраняет Math.Pow как дерево")]
    [TestCategory("Regression")]
    public void Regression_199() => RicisRegressionTestCatalog.Tests[198].Body();

    [TestMethod("INT06: CompoundInterest — отрицательное число периодов отклоняется")]
    [TestCategory("Regression")]
    public void Regression_200() => RicisRegressionTestCatalog.Tests[199].Body();

    [TestMethod("INT07: CompoundInterest — L1 нормализует rate до построения")]
    [TestCategory("Regression")]
    public void Regression_201() => RicisRegressionTestCatalog.Tests[200].Body();

    [TestMethod("AN01: Sin/Cos/Tan — строят явные Math-узлы")]
    [TestCategory("Regression")]
    public void Regression_202() => RicisRegressionTestCatalog.Tests[201].Body();

    [TestMethod("AN02: Exp/Log/Log10/Sqrt — сохраняют аналитические значения")]
    [TestCategory("Regression")]
    public void Regression_203() => RicisRegressionTestCatalog.Tests[202].Body();

    [TestMethod("AN03: Sinh/Cosh/Tanh — строят гиперболические узлы")]
    [TestCategory("Regression")]
    public void Regression_204() => RicisRegressionTestCatalog.Tests[203].Body();

    [TestMethod("AN04: Pow — постоянный показатель совместим с DxDt")]
    [TestCategory("Regression")]
    public void Regression_205() => RicisRegressionTestCatalog.Tests[204].Body();

    [TestMethod("AN05: Pow — отложенный показатель связывается с параметром")]
    [TestCategory("Regression")]
    public void Regression_206() => RicisRegressionTestCatalog.Tests[205].Body();

    [TestMethod("AN06: Аналитический сахар — L1 нормализует вход до Math-узла")]
    [TestCategory("Regression")]
    public void Regression_207() => RicisRegressionTestCatalog.Tests[206].Body();

    [TestMethod("CHK01: Непрерывный сахар совпадает с классическими piecewise-функциями")]
    [TestCategory("Regression")]
    public void Regression_208() => RicisRegressionTestCatalog.Tests[207].Body();

    [TestMethod("CHK02: Комплексные expression-компоненты совпадают с System.Numerics.Complex")]
    [TestCategory("Regression")]
    public void Regression_209() => RicisRegressionTestCatalog.Tests[208].Body();

    [TestMethod("CHK03: CompoundInterest совпадает с прямой формулой Math.Pow")]
    [TestCategory("Regression")]
    public void Regression_210() => RicisRegressionTestCatalog.Tests[209].Body();

    [TestMethod("CHK04: Аналитический сахар совпадает с Math.* на контрольных точках")]
    [TestCategory("Regression")]
    public void Regression_211() => RicisRegressionTestCatalog.Tests[210].Body();

    [TestMethod("CHK05: Производная аналитического Pow совпадает с классической формулой")]
    [TestCategory("Regression")]
    public void Regression_212() => RicisRegressionTestCatalog.Tests[211].Body();

    [TestMethod("QA01: O(1) — int F/0 сохраняет исходный scalar-тип")]
    [TestCategory("Regression")]
    public void Regression_213() => RicisRegressionTestCatalog.Tests[212].Body();

    [TestMethod("QA02: O(1) — BigInteger F·0 сохраняет исходный scalar-тип")]
    [TestCategory("Regression")]
    public void Regression_214() => RicisRegressionTestCatalog.Tests[213].Body();

    [TestMethod("QA03: L1 — Half x/x даёт Half.One в direct pipeline")]
    [TestCategory("Regression")]
    public void Regression_215() => RicisRegressionTestCatalog.Tests[214].Body();

    [TestMethod("QA04: ZERO — 0_F + 0_G даёт 0_{F+G}")]
    [TestCategory("Regression")]
    public void Regression_216() => RicisRegressionTestCatalog.Tests[215].Body();

    [TestMethod("QA05: ZERO — 0_F · 0_G даёт 0_{F·G}")]
    [TestCategory("Regression")]
    public void Regression_217() => RicisRegressionTestCatalog.Tests[216].Body();

    [TestMethod("QA06: L1 — keyed-полюса с разными отображениями ключ→индекс не равны")]
    [TestCategory("Regression")]
    public void Regression_218() => RicisRegressionTestCatalog.Tests[217].Body();

    [TestMethod("QA07: API — roots полюса неизменяемы после построения")]
    [TestCategory("Regression")]
    public void Regression_219() => RicisRegressionTestCatalog.Tests[218].Body();

    [TestMethod("QA08: CompoundInterest — int 5% явно отклоняется без truncation")]
    [TestCategory("Regression")]
    public void Regression_220() => RicisRegressionTestCatalog.Tests[219].Body();

    [TestMethod("QA09: CompoundInterest — BigInteger 100% сохраняет точную форму")]
    [TestCategory("Regression")]
    public void Regression_221() => RicisRegressionTestCatalog.Tests[220].Body();

    [TestMethod("QA10: Abs — Int32.MinValue сообщает overflow вместо отрицательного |x|")]
    [TestCategory("Regression")]
    public void Regression_222() => RicisRegressionTestCatalog.Tests[221].Body();

    [TestMethod("QA11: API — RicisEngine явно отклоняет конечный член")]
    [TestCategory("Regression")]
    public void Regression_223() => RicisRegressionTestCatalog.Tests[222].Body();

    [TestMethod("QA12: ID-03 — разные параметры с одинаковым именем не образуют L1")]
    [TestCategory("Regression")]
    public void Regression_224() => RicisRegressionTestCatalog.Tests[223].Body();

    [TestMethod("QA13: ID-03 — альфа-эквивалентные лямбды остаются одной функцией")]
    [TestCategory("Regression")]
    public void Regression_225() => RicisRegressionTestCatalog.Tests[224].Body();

    [TestMethod("RSH01: private simplifier cleanup сохраняет typed lambda reduction")]
    [TestCategory("Regression")]
    public void Regression_226() => RicisRegressionTestCatalog.Tests[225].Body();

    [TestMethod("RSH02: positive rational Pow exponent сохраняет root lambda")]
    [TestCategory("Regression")]
    public void Regression_227() => RicisRegressionTestCatalog.Tests[226].Body();

    [TestMethod("RSH03: method-call traversal сохраняет method и редуцирует argument")]
    [TestCategory("Regression")]
    public void Regression_228() => RicisRegressionTestCatalog.Tests[227].Body();

    [TestMethod("RSH04: RicisEngine публикует immutable accepted-infinity snapshot")]
    [TestCategory("Regression")]
    public void Regression_229() => RicisRegressionTestCatalog.Tests[228].Body();

    [TestMethod("RSH05: multivariate common-right subtraction сохраняет exact difference")]
    [TestCategory("Regression")]
    public void Regression_230() => RicisRegressionTestCatalog.Tests[229].Body();

    [TestMethod("RC01: ID — тождество F/F выполняется в Phase 0")]
    [TestCategory("Regression")]
    public void Regression_231() => RicisRegressionTestCatalog.Tests[230].Body();

    [TestMethod("RC02: ID — константное 0/0 даёт 1 до A1")]
    [TestCategory("Regression")]
    public void Regression_232() => RicisRegressionTestCatalog.Tests[231].Body();

    [TestMethod("RC03: SP2 — (F·G)/F даёт G")]
    [TestCategory("Regression")]
    public void Regression_233() => RicisRegressionTestCatalog.Tests[232].Body();

    [TestMethod("RC04: SP2 — (F/A)/(G/A) даёт F/G до мостов")]
    [TestCategory("Regression")]
    public void Regression_234() => RicisRegressionTestCatalog.Tests[233].Body();

    [TestMethod("RC05: SP2 — целое 8/4 сворачивается в 2")]
    [TestCategory("Regression")]
    public void Regression_235() => RicisRegressionTestCatalog.Tests[234].Body();

    [TestMethod("RC06: SP2 — дробь 1/2 остаётся деревом Divide")]
    [TestCategory("Regression")]
    public void Regression_236() => RicisRegressionTestCatalog.Tests[235].Body();

    [TestMethod("RC07: A4 — остаточная форма 0_F/0_G сохраняется как F/G")]
    [TestCategory("Regression")]
    public void Regression_237() => RicisRegressionTestCatalog.Tests[236].Body();

    [TestMethod("RC08: A5 — разные ∞_F/∞_G дают F/G")]
    [TestCategory("Regression")]
    public void Regression_238() => RicisRegressionTestCatalog.Tests[237].Body();

    [TestMethod("RC09: A5 — одинаковые ∞_F/∞_F дают 1")]
    [TestCategory("Regression")]
    public void Regression_239() => RicisRegressionTestCatalog.Tests[238].Body();

    [TestMethod("RC10: A6 — 0_F·∞_G даёт F·G")]
    [TestCategory("Regression")]
    public void Regression_240() => RicisRegressionTestCatalog.Tests[239].Body();

    [TestMethod("RC11: A7 — ∞_F+∞_G даёт ∞_{F+G}")]
    [TestCategory("Regression")]
    public void Regression_241() => RicisRegressionTestCatalog.Tests[240].Body();

    [TestMethod("RC12: A7 — ∞_F−∞_G даёт ∞_{F−G}")]
    [TestCategory("Regression")]
    public void Regression_242() => RicisRegressionTestCatalog.Tests[241].Body();

    [TestMethod("RC13: A7 — ∞_F·∞_G даёт ∞_{F·G}")]
    [TestCategory("Regression")]
    public void Regression_243() => RicisRegressionTestCatalog.Tests[242].Body();

    [TestMethod("RC14: scalar — C·∞_F даёт ∞_{C·F}")]
    [TestCategory("Regression")]
    public void Regression_244() => RicisRegressionTestCatalog.Tests[243].Body();

    [TestMethod("RC15: scalar — ∞_F·C даёт ∞_{F·C}")]
    [TestCategory("Regression")]
    public void Regression_245() => RicisRegressionTestCatalog.Tests[244].Body();

    [TestMethod("RC16: scalar — ∞_F/C даёт ∞_{F/C}")]
    [TestCategory("Regression")]
    public void Regression_246() => RicisRegressionTestCatalog.Tests[245].Body();

    [TestMethod("RC17: A1 — F/0 даёт ∞_F")]
    [TestCategory("Regression")]
    public void Regression_247() => RicisRegressionTestCatalog.Tests[246].Body();

    [TestMethod("RC18: LIM — F·0 даёт 0_F")]
    [TestCategory("Regression")]
    public void Regression_248() => RicisRegressionTestCatalog.Tests[247].Body();

    [TestMethod("RC19: LIM — F/0 даёт ∞_F")]
    [TestCategory("Regression")]
    public void Regression_249() => RicisRegressionTestCatalog.Tests[248].Body();

    [TestMethod("RC20: POL — sin(π/2) даёт 1")]
    [TestCategory("Regression")]
    public void Regression_250() => RicisRegressionTestCatalog.Tests[249].Body();

    [TestMethod("RC21: POL — tan(π/2) даёт ∞₁")]
    [TestCategory("Regression")]
    public void Regression_251() => RicisRegressionTestCatalog.Tests[250].Body();

    [TestMethod("RC22: ROOT — разные наборы корней не объединяются")]
    [TestCategory("Regression")]
    public void Regression_252() => RicisRegressionTestCatalog.Tests[251].Body();

    [TestMethod("RC23: SP2 — (x²−25)/(x−5) даёт x+5")]
    [TestCategory("Regression")]
    public void Regression_253() => RicisRegressionTestCatalog.Tests[252].Body();

    [TestMethod("RC24: A1 — 1/(x²−4) хранит оба ключа")]
    [TestCategory("Regression")]
    public void Regression_254() => RicisRegressionTestCatalog.Tests[253].Body();

    [TestMethod("RC25: A1 — 1/(1−x)^(2/3) хранит x=1")]
    [TestCategory("Regression")]
    public void Regression_255() => RicisRegressionTestCatalog.Tests[254].Body();

    [TestMethod("RC26: SP2/A1 — 1/(1−2/x) даёт ∞₂ при x=2")]
    [TestCategory("Regression")]
    public void Regression_256() => RicisRegressionTestCatalog.Tests[255].Body();

    [TestMethod("RC27: A1 — 1/(1−tan x) не получает полюса tan")]
    [TestCategory("Regression")]
    public void Regression_257() => RicisRegressionTestCatalog.Tests[256].Body();

    [TestMethod("RC28: SP4 — близкие корни не сливаются")]
    [TestCategory("Regression")]
    public void Regression_258() => RicisRegressionTestCatalog.Tests[257].Body();

    [TestMethod("RC29: A1 — x²/(a·x²+a·b+c) даёт ∞₁ для обоих ключей")]
    [TestCategory("Regression")]
    public void Regression_259() => RicisRegressionTestCatalog.Tests[258].Body();

    [TestMethod("RC30: ID — параметризованная форма x²/x² даёт 1")]
    [TestCategory("Regression")]
    public void Regression_260() => RicisRegressionTestCatalog.Tests[259].Body();

    [TestMethod("RC31: SP2 — x²/(2x²) оставляет точное 1/2")]
    [TestCategory("Regression")]
    public void Regression_261() => RicisRegressionTestCatalog.Tests[260].Body();

    [TestMethod("RC32: A1 — x/(x²−1) сохраняет разные индексы в своих ключах")]
    [TestCategory("Regression")]
    public void Regression_262() => RicisRegressionTestCatalog.Tests[261].Body();

    [TestMethod("RC33: META — захваченный about добавляет SEO-профиль автора")]
    [TestCategory("Regression")]
    public void Regression_263() => RicisRegressionTestCatalog.Tests[262].Body();

    [TestMethod("RC34: META — параметр about добавляет SEO-профиль автора")]
    [TestCategory("Regression")]
    public void Regression_264() => RicisRegressionTestCatalog.Tests[263].Body();

    [TestMethod("RC35: META — профиль about сохраняет все подтверждённые источники")]
    [TestCategory("Regression")]
    public void Regression_265() => RicisRegressionTestCatalog.Tests[264].Body();

    [TestMethod("RC36: ID — sign(x)/sign(x) даёт 1")]
    [TestCategory("Regression")]
    public void Regression_266() => RicisRegressionTestCatalog.Tests[265].Body();

    [TestMethod("RC37: ID — clamp(x)/clamp(x) даёт 1")]
    [TestCategory("Regression")]
    public void Regression_267() => RicisRegressionTestCatalog.Tests[266].Body();

    [TestMethod("RC38: SP2 — abs(x) сокращается как общий множитель")]
    [TestCategory("Regression")]
    public void Regression_268() => RicisRegressionTestCatalog.Tests[267].Body();

    [TestMethod("RC39: ID — x%2/(x%2) даёт 1")]
    [TestCategory("Regression")]
    public void Regression_269() => RicisRegressionTestCatalog.Tests[268].Body();

    [TestMethod("RC40: ID — условная отсечка F/F даёт 1")]
    [TestCategory("Regression")]
    public void Regression_270() => RicisRegressionTestCatalog.Tests[269].Body();

    [TestMethod("RC41: SP2 — F^n/F^(n−1) даёт F структурно")]
    [TestCategory("Regression")]
    public void Regression_271() => RicisRegressionTestCatalog.Tests[270].Body();

    [TestMethod("RC42: SP2 — a^N/a^(N−X) даёт a^X структурно")]
    [TestCategory("Regression")]
    public void Regression_272() => RicisRegressionTestCatalog.Tests[271].Body();

    [TestMethod("RC43: ID — аналитические F/F сокращаются для Log/Sqrt/Exp/Trig")]
    [TestCategory("Regression")]
    public void Regression_273() => RicisRegressionTestCatalog.Tests[272].Body();

    [TestMethod("RC44: ALG — F−0 даёт F")]
    [TestCategory("Regression")]
    public void Regression_274() => RicisRegressionTestCatalog.Tests[273].Body();

    [TestMethod("RC45: ALG — 0−F даёт −F")]
    [TestCategory("Regression")]
    public void Regression_275() => RicisRegressionTestCatalog.Tests[274].Body();

    [TestMethod("RC46: ALG — F−F даёт обычный ноль")]
    [TestCategory("Regression")]
    public void Regression_276() => RicisRegressionTestCatalog.Tests[275].Body();

    [TestMethod("RC47: ALG — −(−F) даёт F")]
    [TestCategory("Regression")]
    public void Regression_277() => RicisRegressionTestCatalog.Tests[276].Body();

    [TestMethod("RC48: CONTROL — a^N/a^(N−X) проходит полный pipeline")]
    [TestCategory("Regression")]
    public void Regression_278() => RicisRegressionTestCatalog.Tests[277].Body();

    [TestMethod("RC49: CONTROL — новые ALG rules не меняют 0_F payload")]
    [TestCategory("Regression")]
    public void Regression_279() => RicisRegressionTestCatalog.Tests[278].Body();

    [TestMethod("CS01: public simplifier строит typed zero для double F·0")]
    [TestCategory("Regression")]
    public void Regression_280() => RicisRegressionTestCatalog.Tests[279].Body();

    [TestMethod("CS02: BigInteger x·x сохраняется без неподдерживаемого Power")]
    [TestCategory("Regression")]
    public void Regression_281() => RicisRegressionTestCatalog.Tests[280].Body();

    [TestMethod("CS03: F/KeyedInfinity даёт 0_F с полными ключами")]
    [TestCategory("Regression")]
    public void Regression_282() => RicisRegressionTestCatalog.Tests[281].Body();

    [TestMethod("CS04: proof отклоняет non-finite pressure constants")]
    [TestCategory("Regression")]
    public void Regression_283() => RicisRegressionTestCatalog.Tests[282].Body();

    [TestMethod("CS05: -0_F распознаётся как indexed zero")]
    [TestCategory("Regression")]
    public void Regression_284() => RicisRegressionTestCatalog.Tests[283].Body();

    [TestMethod("CS06: traversal PoleInfinity не вызывает Reduce")]
    [TestCategory("Regression")]
    public void Regression_285() => RicisRegressionTestCatalog.Tests[284].Body();

    [TestMethod("CS07: traversal ZeroInfinity сохраняет deferred numerator")]
    [TestCategory("Regression")]
    public void Regression_286() => RicisRegressionTestCatalog.Tests[285].Body();

    [TestMethod("CS08: comparer различает полные root multisets")]
    [TestCategory("Regression")]
    public void Regression_287() => RicisRegressionTestCatalog.Tests[286].Body();

    [TestMethod("CS09: Compose сохраняет indexed zero")]
    [TestCategory("Regression")]
    public void Regression_288() => RicisRegressionTestCatalog.Tests[287].Body();

    [TestMethod("SAFE01: pipeline не исполняет caller MethodCall при поиске корней")]
    [TestCategory("Regression")]
    public void Regression_289() => RicisRegressionTestCatalog.Tests[288].Body();

    [TestMethod("SAFE02: дробный индексированный zero сохраняет тип Double")]
    [TestCategory("Regression")]
    public void Regression_290() => RicisRegressionTestCatalog.Tests[289].Body();

    [TestMethod("SAFE03: LazyInfinity не исполняет небезопасный payload при Reduce")]
    [TestCategory("Regression")]
    public void Regression_291() => RicisRegressionTestCatalog.Tests[290].Body();

    [TestMethod("LOG01: true && x и x && true редуцируются в x")]
    [TestCategory("Regression")]
    public void Regression_292() => RicisRegressionTestCatalog.Tests[291].Body();

    [TestMethod("LOG02: false || x и x || false редуцируются в x")]
    [TestCategory("Regression")]
    public void Regression_293() => RicisRegressionTestCatalog.Tests[292].Body();

    [TestMethod("LOG03: двойное отрицание bool редуцируется")]
    [TestCategory("Regression")]
    public void Regression_294() => RicisRegressionTestCatalog.Tests[293].Body();

    [TestMethod("LOG04: константное отрицание редуцируется")]
    [TestCategory("Regression")]
    public void Regression_295() => RicisRegressionTestCatalog.Tests[294].Body();

    [TestMethod("LOG05: constant conditional выбирает ветвь")]
    [TestCategory("Regression")]
    public void Regression_296() => RicisRegressionTestCatalog.Tests[295].Body();

    [TestMethod("LOG06: одинаковые conditional branches сохраняют вычисление test")]
    [TestCategory("Regression")]
    public void Regression_297() => RicisRegressionTestCatalog.Tests[296].Body();

    [TestMethod("LOG07: опасные short-circuit rewrites запрещены")]
    [TestCategory("Regression")]
    public void Regression_298() => RicisRegressionTestCatalog.Tests[297].Body();

    [TestMethod("LOG08: logical stage виден в phase trace")]
    [TestCategory("Regression")]
    public void Regression_299() => RicisRegressionTestCatalog.Tests[298].Body();

    [TestMethod("LOG09: Quine-McCluskey минимизирует a·b + a·¬b до a")]
    [TestCategory("Regression")]
    public void Regression_300() => RicisRegressionTestCatalog.Tests[299].Body();

    [TestMethod("VECTOR01: вектор хранит N упорядоченных координат")]
    [TestCategory("Regression")]
    public void Regression_301() => RicisRegressionTestCatalog.Tests[300].Body();

    [TestMethod("VECTOR02: координаты защищены от изменения входного массива")]
    [TestCategory("Regression")]
    public void Regression_302() => RicisRegressionTestCatalog.Tests[301].Body();

    [TestMethod("VECTOR03: сложение и вычитание выполняются покомпонентно")]
    [TestCategory("Regression")]
    public void Regression_303() => RicisRegressionTestCatalog.Tests[302].Body();

    [TestMethod("VECTOR04: масштабирование и dot product используют INumber<T>")]
    [TestCategory("Regression")]
    public void Regression_304() => RicisRegressionTestCatalog.Tests[303].Body();

    [TestMethod("VECTOR05: Zero создаёт типизированный нулевой вектор")]
    [TestCategory("Regression")]
    public void Regression_305() => RicisRegressionTestCatalog.Tests[304].Body();

    [TestMethod("VECTOR06: разные размерности отклоняются явно")]
    [TestCategory("Regression")]
    public void Regression_306() => RicisRegressionTestCatalog.Tests[305].Body();

    [TestMethod("VECTOR07: пустой вектор отклоняется")]
    [TestCategory("Regression")]
    public void Regression_307() => RicisRegressionTestCatalog.Tests[306].Body();

    [TestMethod("VECTOR08: generic BigInteger поддерживает векторные операции")]
    [TestCategory("Regression")]
    public void Regression_308() => RicisRegressionTestCatalog.Tests[307].Body();

    [TestMethod("VEX01: символьный вектор сохраняет N lambda-координат")]
    [TestCategory("Regression")]
    public void Regression_309() => RicisRegressionTestCatalog.Tests[308].Body();

    [TestMethod("VEX02: символьное сложение выполняется покомпонентно")]
    [TestCategory("Regression")]
    public void Regression_310() => RicisRegressionTestCatalog.Tests[309].Body();

    [TestMethod("VEX03: Zero expression vector сохраняет структурный ноль")]
    [TestCategory("Regression")]
    public void Regression_311() => RicisRegressionTestCatalog.Tests[310].Body();

    [TestMethod("VEX04: треугольные F и G строятся как векторные отображения")]
    [TestCategory("Regression")]
    public void Regression_312() => RicisRegressionTestCatalog.Tests[311].Body();

    [TestMethod("VEX05: композиция векторных отображений сохраняет размерность")]
    [TestCategory("Regression")]
    public void Regression_313() => RicisRegressionTestCatalog.Tests[312].Body();

    [TestMethod("VEX06: несовместимые сигнатуры отклоняются")]
    [TestCategory("Regression")]
    public void Regression_314() => RicisRegressionTestCatalog.Tests[313].Body();

    [TestMethod("ES01: ExpressionSystem сохраняет все lambda-выражения")]
    [TestCategory("Regression")]
    public void Regression_315() => RicisRegressionTestCatalog.Tests[314].Body();

    [TestMethod("ES02: ExpressionSystem сохраняет общую сигнатуру")]
    [TestCategory("Regression")]
    public void Regression_316() => RicisRegressionTestCatalog.Tests[315].Body();

    [TestMethod("ES03: ExpressionSystem использует существующий vector overload")]
    [TestCategory("Regression")]
    public void Regression_317() => RicisRegressionTestCatalog.Tests[316].Body();

    [TestMethod("ES04: ExpressionSystem отклоняет несовместимые сигнатуры")]
    [TestCategory("Regression")]
    public void Regression_318() => RicisRegressionTestCatalog.Tests[317].Body();

    [TestMethod("ES05: ExpressionSystem не схлопывается в скаляр")]
    [TestCategory("Regression")]
    public void Regression_319() => RicisRegressionTestCatalog.Tests[318].Body();

    [TestMethod("API17: ExpressionSystem exposes structural-zero and vector interoperability APIs")]
    [TestCategory("Regression")]
    public void Regression_320() => RicisRegressionTestCatalog.Tests[319].Body();

    [TestMethod("MEX01: матрица хранит общую сигнатуру элементов")]
    [TestCategory("Regression")]
    public void Regression_321() => RicisRegressionTestCatalog.Tests[320].Body();

    [TestMethod("MEX02: determinant 2x2 строится как RICIS expression")]
    [TestCategory("Regression")]
    public void Regression_322() => RicisRegressionTestCatalog.Tests[321].Body();

    [TestMethod("MEX03: нулевая матрица распознаётся структурно")]
    [TestCategory("Regression")]
    public void Regression_323() => RicisRegressionTestCatalog.Tests[322].Body();

    [TestMethod("MEX04: determinant отклоняет матрицу не 2x2")]
    [TestCategory("Regression")]
    public void Regression_324() => RicisRegressionTestCatalog.Tests[323].Body();

    [TestMethod("MEX05: determinant 3x3 нормализует треугольную матрицу в 1")]
    [TestCategory("Regression")]
    public void Regression_325() => RicisRegressionTestCatalog.Tests[324].Body();

    [TestMethod("API18: matrix exposes immutable row view")]
    [TestCategory("Regression")]
    public void Regression_326() => RicisRegressionTestCatalog.Tests[325].Body();

    [TestMethod("JSG01: сингулярный determinant сохраняется как индексированный zero")]
    [TestCategory("Regression")]
    public void Regression_327() => RicisRegressionTestCatalog.Tests[326].Body();

    [TestMethod("JSG02: A6 возвращает determinant·inverse payload без NaN")]
    [TestCategory("Regression")]
    public void Regression_328() => RicisRegressionTestCatalog.Tests[327].Body();

    [TestMethod("JSG03: несколько inverse payload entries обрабатываются покомпонентно")]
    [TestCategory("Regression")]
    public void Regression_329() => RicisRegressionTestCatalog.Tests[328].Body();

    [TestMethod("JSG04: пустой inverse payload отклоняется")]
    [TestCategory("Regression")]
    public void Regression_330() => RicisRegressionTestCatalog.Tests[329].Body();

    [TestMethod("JPR01: Jacobian proof принимает независимые lambda-посылки и lambda verification")]
    [TestCategory("Regression")]
    public void Regression_331() => RicisRegressionTestCatalog.Tests[330].Body();

    [TestMethod("JPR02: Jacobian proof публикует полный typed node-to-root trace")]
    [TestCategory("Regression")]
    public void Regression_332() => RicisRegressionTestCatalog.Tests[331].Body();

    [TestMethod("JPR03: Jacobian proof экспортирует standalone LaTeX и compilable structured Lean")]
    [TestCategory("Regression")]
    public void Regression_333() => RicisRegressionTestCatalog.Tests[332].Body();

    [TestMethod("JPR04: Jacobian proof сохраняет A6 payload без классического inverse")]
    [TestCategory("Regression")]
    public void Regression_334() => RicisRegressionTestCatalog.Tests[333].Body();

    [TestMethod("RIP01: F/0 преобразуется внутренним O(1)-мостом в indexed infinity")]
    [TestCategory("Regression")]
    public void Regression_335() => RicisRegressionTestCatalog.Tests[334].Body();

    [TestMethod("RIP02: F·0 преобразуется внутренним O(1)-мостом в indexed zero")]
    [TestCategory("Regression")]
    public void Regression_336() => RicisRegressionTestCatalog.Tests[335].Body();

    [TestMethod("RIP03: A6 возвращает payload expression без классического 0·∞")]
    [TestCategory("Regression")]
    public void Regression_337() => RicisRegressionTestCatalog.Tests[336].Body();

    [TestMethod("RIP04: сингулярный payload сохраняет certified keys")]
    [TestCategory("Regression")]
    public void Regression_338() => RicisRegressionTestCatalog.Tests[337].Body();

    [TestMethod("VVIS01: Visitor доказывает G∘F=Id₃")]
    [TestCategory("Regression")]
    public void Regression_339() => RicisRegressionTestCatalog.Tests[338].Body();

    [TestMethod("VVIS02: Visitor доказывает F∘G=Id₃")]
    [TestCategory("Regression")]
    public void Regression_340() => RicisRegressionTestCatalog.Tests[339].Body();

    [TestMethod("VVIS03: Visitor отклоняет ложное векторное тождество")]
    [TestCategory("Regression")]
    public void Regression_341() => RicisRegressionTestCatalog.Tests[340].Body();

    [TestMethod("VVIS04: Visitor оставляет residual как vector expression")]
    [TestCategory("Regression")]
    public void Regression_342() => RicisRegressionTestCatalog.Tests[341].Body();

    [TestMethod("SP3: TypeConsistency сохраняет indexed-zero payload и тот же узел")]
    [TestCategory("Regression")]
    public void Regression_343() => RicisRegressionTestCatalog.Tests[342].Body();

    [TestMethod("SP3: TypeConsistency сохраняет indexed-infinity payload и ключ")]
    [TestCategory("Regression")]
    public void Regression_344() => RicisRegressionTestCatalog.Tests[343].Body();

    [TestMethod("SP3: TypeConsistency отклоняет несертифицированный бесконечный ключ")]
    [TestCategory("Regression")]
    public void Regression_345() => RicisRegressionTestCatalog.Tests[344].Body();

    [TestMethod("TLOG01: typed journal сохраняет общий порядок и реальные stage types")]
    [TestCategory("Regression")]
    public void Regression_346() => RicisRegressionTestCatalog.Tests[345].Body();

    [TestMethod("TLOG02: proof pipeline публикует visitor trace без исполнения условий")]
    [TestCategory("Regression")]
    public void Regression_347() => RicisRegressionTestCatalog.Tests[346].Body();

    [TestMethod("TLOG03: JSON LaTeX Lean reports рендерят один canonical snapshot")]
    [TestCategory("Regression")]
    public void Regression_348() => RicisRegressionTestCatalog.Tests[347].Body();

    [TestMethod("TLOG04: renderer отклоняет неупорядоченный journal и неизвестный format")]
    [TestCategory("Regression")]
    public void Regression_349() => RicisRegressionTestCatalog.Tests[348].Body();

    [TestMethod("API22: SimplifyWithLog publishes typed public pipeline audit")]
    [TestCategory("Regression")]
    public void Regression_350() => RicisRegressionTestCatalog.Tests[349].Body();

    [TestMethod("GNP01: generic Simplify returns typed INumber identity")]
    [TestCategory("Regression")]
    public void Regression_351() => RicisRegressionTestCatalog.Tests[350].Body();

    [TestMethod("GNP02: generic SimplifyWithTrace records normative phases")]
    [TestCategory("Regression")]
    public void Regression_352() => RicisRegressionTestCatalog.Tests[351].Body();

    [TestMethod("GNP03: generic SimplifyWithLog publishes typed audit")]
    [TestCategory("Regression")]
    public void Regression_353() => RicisRegressionTestCatalog.Tests[352].Body();

    [TestMethod("GNP04: generic SimplifyWithTraceAndLog preserves both journals")]
    [TestCategory("Regression")]
    public void Regression_354() => RicisRegressionTestCatalog.Tests[353].Body();

    [TestMethod("GNP05: generic unsigned subtraction does not fabricate unary negate")]
    [TestCategory("Regression")]
    public void Regression_355() => RicisRegressionTestCatalog.Tests[354].Body();

    [TestMethod("CHECKED01: ProveChecked принимает реальные conditions/constraints и проверяет expected")]
    [TestCategory("Regression")]
    public void Regression_356() => RicisRegressionTestCatalog.Tests[355].Body();

    [TestMethod("CHECKED02: ProveChecked отклоняет структурно неверный expected")]
    [TestCategory("Regression")]
    public void Regression_357() => RicisRegressionTestCatalog.Tests[356].Body();

    [TestMethod("CHECKED03: ProveChecked корректно rebinding-ит параметр expected")]
    [TestCategory("Regression")]
    public void Regression_358() => RicisRegressionTestCatalog.Tests[357].Body();

    [TestMethod("CHECKED04: ProveChecked не исполняет реальные lambda conditions")]
    [TestCategory("Regression")]
    public void Regression_359() => RicisRegressionTestCatalog.Tests[358].Body();

    [TestMethod("CHECKED05: ProveDocumentChecked публикует verification expression")]
    [TestCategory("Regression")]
    public void Regression_360() => RicisRegressionTestCatalog.Tests[359].Body();

    [TestMethod("PDF01: Log template — выводит trace и возвращает то же производное дерево")]
    [TestCategory("Regression")]
    public void Regression_361() => RicisRegressionTestCatalog.Tests[360].Body();

    [TestMethod("PDF02: Academic template — применяет Func<string,string> без изменения вывода")]
    [TestCategory("Regression")]
    public void Regression_362() => RicisRegressionTestCatalog.Tests[361].Body();

    [TestMethod("PDF03: Generic Lean format — controlled rejection для unsupported shape")]
    [TestCategory("Regression")]
    public void Regression_363() => RicisRegressionTestCatalog.Tests[362].Body();

    [TestMethod("PDF04: Json template — сохраняет полный node-to-root маршрут")]
    [TestCategory("Regression")]
    public void Regression_364() => RicisRegressionTestCatalog.Tests[363].Body();

    [TestMethod("PDF05: LaTeX template — сохраняет полный node-to-root маршрут")]
    [TestCategory("Regression")]
    public void Regression_365() => RicisRegressionTestCatalog.Tests[364].Body();

    [TestMethod("LFT01: StructuredData и RequestedRows создают LeanDoc")]
    [TestCategory("Regression")]
    public void Regression_366() => RicisRegressionTestCatalog.Tests[365].Body();

    [TestMethod("LFT02: RequestedRows раскрывает theorem dependencies")]
    [TestCategory("Regression")]
    public void Regression_367() => RicisRegressionTestCatalog.Tests[366].Body();

    [TestMethod("LFT03: StructuredData блокирует небезопасные Lean identifiers")]
    [TestCategory("Regression")]
    public void Regression_368() => RicisRegressionTestCatalog.Tests[367].Body();

    [TestMethod("PDF06: Format API — отклоняет неизвестный enum и null callback")]
    [TestCategory("Regression")]
    public void Regression_369() => RicisRegressionTestCatalog.Tests[368].Body();

    [TestMethod("PDF07: Binary overload — использует общий Log renderer")]
    [TestCategory("Regression")]
    public void Regression_370() => RicisRegressionTestCatalog.Tests[369].Body();

    [TestMethod("PDF08: Injected ILog сохраняет полный typed node-to-root документ")]
    [TestCategory("Regression")]
    public void Regression_371() => RicisRegressionTestCatalog.Tests[370].Body();

    [TestMethod("PDF09: Checked multi-format API строит один verified proof и сохраняет маршрут")]
    [TestCategory("Regression")]
    public void Regression_372() => RicisRegressionTestCatalog.Tests[371].Body();

    [TestMethod("SQA01: сложная multi-key singularity сохраняет RICIS A6 payload")]
    [TestCategory("Regression")]
    public void Regression_373() => RicisRegressionTestCatalog.Tests[372].Body();

    [TestMethod("SQA02: классическая оценка singularity не определена, RICIS result структурен")]
    [TestCategory("Regression")]
    public void Regression_374() => RicisRegressionTestCatalog.Tests[373].Body();

    [TestMethod("SQA03: сложная singularity генерирует structured A6 LeanDoc")]
    [TestCategory("Regression")]
    public void Regression_375() => RicisRegressionTestCatalog.Tests[374].Body();

    [TestMethod("LRL01: longest route Lean source содержит десять узлов, девять checkpoint и terminal theorem")]
    [TestCategory("Regression")]
    public void Regression_376() => RicisRegressionTestCatalog.Tests[375].Body();

    [TestMethod("LRL02: longest route Lean source не подменяет route composition внешними научными claims")]
    [TestCategory("Regression")]
    public void Regression_377() => RicisRegressionTestCatalog.Tests[376].Body();

    [TestMethod("LRL03: longest route Lean artifact зарегистрирован как mandatory kernel knowledge source")]
    [TestCategory("Regression")]
    public void Regression_378() => RicisRegressionTestCatalog.Tests[377].Body();

    [TestMethod("CRL01: concrete route Lean source содержит root, десять node labels и depth 0–9 proofs")]
    [TestCategory("Regression")]
    public void Regression_379() => RicisRegressionTestCatalog.Tests[378].Body();

    [TestMethod("CRL02: concrete route Lean source задаёт rank-one determinant and explicit invariant")]
    [TestCategory("Regression")]
    public void Regression_380() => RicisRegressionTestCatalog.Tests[379].Body();

    [TestMethod("CRL03: concrete route Lean source не использует certificate fields или admitted proof")]
    [TestCategory("Regression")]
    public void Regression_381() => RicisRegressionTestCatalog.Tests[380].Body();
}
