#!/usr/bin/env python3
"""Generate the DRY mixed-integral ULong2048 operator surface."""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "Ricis.Numerics" / "ULong2048.IntegralOperators.generated.cs"
TEST_TARGET = ROOT / "Ricis.Numerics" / "Ricis.Numerics.UnitTests" / "ULong2048IntegralOperators.generated.cs"

UNSIGNED = ["byte", "ushort", "uint", "ulong", "nuint", "UInt128"]
SIGNED = ["sbyte", "short", "int", "long", "nint", "Int128"]

HEADER = """// <auto-generated />
// Generated by scripts/generate_ulong2048_integral_operators.py. Do not hand edit.
#nullable enable
#pragma warning disable CS1591

using System.Numerics;

namespace Ricis.Numerics;

public readonly partial struct ULong2048
{
    private static ULong2048 PromoteUnsigned(byte value) => new(value);
    private static ULong2048 PromoteUnsigned(ushort value) => new(value);
    private static ULong2048 PromoteUnsigned(uint value) => new(value);
    private static ULong2048 PromoteUnsigned(ulong value) => new(value);
    private static ULong2048 PromoteUnsigned(nuint value) => new((ulong)value);
    private static ULong2048 PromoteUnsigned(UInt128 value)
    {
        ULong2048Limbs limbs = default;
        limbs[0] = (ulong)value;
        limbs[1] = (ulong)(value >> 64);
        return new ULong2048(limbs);
    }

    private static BigInteger PromoteSigned(sbyte value) => new(value);
    private static BigInteger PromoteSigned(short value) => new(value);
    private static BigInteger PromoteSigned(int value) => new(value);
    private static BigInteger PromoteSigned(long value) => new(value);
    private static BigInteger PromoteSigned(nint value) => new(value);
    private static BigInteger PromoteSigned(Int128 value) => BigInteger.Parse(value.ToString());

    private static int NormalizeShift(UInt128 value) => value >= BitCount ? BitCount : (int)value;
    private static int NormalizeShift(Int128 value) => value >= BitCount ? BitCount : value <= -BitCount ? -BitCount : (int)value;
    public static ULong2048 operator <<(ULong2048 value, uint shift) => ShiftLeft(in value, NormalizeShift((UInt128)shift));
    public static ULong2048 operator >>(ULong2048 value, uint shift) => ShiftRight(in value, NormalizeShift((UInt128)shift));
    public static ULong2048 operator >>>(ULong2048 value, uint shift) => ShiftRight(in value, NormalizeShift((UInt128)shift));
    public static ULong2048 operator <<(ULong2048 value, ulong shift) => ShiftLeft(in value, NormalizeShift((UInt128)shift));
    public static ULong2048 operator >>(ULong2048 value, ulong shift) => ShiftRight(in value, NormalizeShift((UInt128)shift));
    public static ULong2048 operator >>>(ULong2048 value, ulong shift) => ShiftRight(in value, NormalizeShift((UInt128)shift));
    public static ULong2048 operator <<(ULong2048 value, nuint shift) => ShiftLeft(in value, NormalizeShift((UInt128)shift));
    public static ULong2048 operator >>(ULong2048 value, nuint shift) => ShiftRight(in value, NormalizeShift((UInt128)shift));
    public static ULong2048 operator >>>(ULong2048 value, nuint shift) => ShiftRight(in value, NormalizeShift((UInt128)shift));
    public static ULong2048 operator <<(ULong2048 value, UInt128 shift) => ShiftLeft(in value, NormalizeShift(shift));
    public static ULong2048 operator >>(ULong2048 value, UInt128 shift) => ShiftRight(in value, NormalizeShift(shift));
    public static ULong2048 operator >>>(ULong2048 value, UInt128 shift) => ShiftRight(in value, NormalizeShift(shift));
    public static ULong2048 operator <<(ULong2048 value, long shift) => ShiftLeft(in value, NormalizeShift((Int128)shift));
    public static ULong2048 operator >>(ULong2048 value, long shift) => ShiftRight(in value, NormalizeShift((Int128)shift));
    public static ULong2048 operator >>>(ULong2048 value, long shift) => ShiftRight(in value, NormalizeShift((Int128)shift));
    public static ULong2048 operator <<(ULong2048 value, nint shift) => ShiftLeft(in value, NormalizeShift((Int128)shift));
    public static ULong2048 operator >>(ULong2048 value, nint shift) => ShiftRight(in value, NormalizeShift((Int128)shift));
    public static ULong2048 operator >>>(ULong2048 value, nint shift) => ShiftRight(in value, NormalizeShift((Int128)shift));
    public static ULong2048 operator <<(ULong2048 value, Int128 shift) => ShiftLeft(in value, NormalizeShift(shift));
    public static ULong2048 operator >>(ULong2048 value, Int128 shift) => ShiftRight(in value, NormalizeShift(shift));
    public static ULong2048 operator >>>(ULong2048 value, Int128 shift) => ShiftRight(in value, NormalizeShift(shift));

"""


def unsigned_block(t: str) -> str:
    p = f"PromoteUnsigned(right)"
    q = f"PromoteUnsigned(left)"
    return f"""    public static ULong2048 operator +(ULong2048 left, {t} right) => left + {p};
    public static ULong2048 operator +({t} left, ULong2048 right) => {q} + right;
    public static ULong2048 operator -(ULong2048 left, {t} right) => left - {p};
    public static ULong2048 operator -({t} left, ULong2048 right) => {q} - right;
    public static ULong2048 operator *(ULong2048 left, {t} right) => left * {p};
    public static ULong2048 operator *({t} left, ULong2048 right) => {q} * right;
    public static ULong2048 operator /(ULong2048 left, {t} right) => left / {p};
    public static ULong2048 operator /({t} left, ULong2048 right) => {q} / right;
    public static ULong2048 operator %(ULong2048 left, {t} right) => left % {p};
    public static ULong2048 operator %({t} left, ULong2048 right) => {q} % right;
    public static ULong2048 operator &(ULong2048 left, {t} right) => left & {p};
    public static ULong2048 operator &({t} left, ULong2048 right) => {q} & right;
    public static ULong2048 operator |(ULong2048 left, {t} right) => left | {p};
    public static ULong2048 operator |({t} left, ULong2048 right) => {q} | right;
    public static ULong2048 operator ^(ULong2048 left, {t} right) => left ^ {p};
    public static ULong2048 operator ^({t} left, ULong2048 right) => {q} ^ right;
    public static bool operator ==(ULong2048 left, {t} right) => left == {p};
    public static bool operator ==({t} left, ULong2048 right) => {q} == right;
    public static bool operator !=(ULong2048 left, {t} right) => left != {p};
    public static bool operator !=({t} left, ULong2048 right) => {q} != right;
    public static bool operator <(ULong2048 left, {t} right) => left < {p};
    public static bool operator <({t} left, ULong2048 right) => {q} < right;
    public static bool operator <=(ULong2048 left, {t} right) => left <= {p};
    public static bool operator <=({t} left, ULong2048 right) => {q} <= right;
    public static bool operator >(ULong2048 left, {t} right) => left > {p};
    public static bool operator >({t} left, ULong2048 right) => {q} > right;
    public static bool operator >=(ULong2048 left, {t} right) => left >= {p};
    public static bool operator >=({t} left, ULong2048 right) => {q} >= right;
    public static ULong2048 operator checked +(ULong2048 left, {t} right) => checked(left + {p});
    public static ULong2048 operator checked +({t} left, ULong2048 right) => checked({q} + right);
    public static ULong2048 operator checked -(ULong2048 left, {t} right) => CheckedSubtract(left, {p});
    public static ULong2048 operator checked -({t} left, ULong2048 right) => CheckedSubtract({q}, right);
    public static ULong2048 operator checked *(ULong2048 left, {t} right) => CheckedMultiply(left, {p});
    public static ULong2048 operator checked *({t} left, ULong2048 right) => CheckedMultiply({q}, right);

"""


def signed_block(t: str) -> str:
    p = f"PromoteSigned(right)"
    q = f"PromoteSigned(left)"
    return f"""    public static BigInteger operator +(ULong2048 left, {t} right) => left.ToBigInteger() + {p};
    public static BigInteger operator +({t} left, ULong2048 right) => {q} + right.ToBigInteger();
    public static BigInteger operator -(ULong2048 left, {t} right) => left.ToBigInteger() - {p};
    public static BigInteger operator -({t} left, ULong2048 right) => {q} - right.ToBigInteger();
    public static BigInteger operator *(ULong2048 left, {t} right) => left.ToBigInteger() * {p};
    public static BigInteger operator *({t} left, ULong2048 right) => {q} * right.ToBigInteger();
    public static BigInteger operator /(ULong2048 left, {t} right) => left.ToBigInteger() / {p};
    public static BigInteger operator /({t} left, ULong2048 right) => {q} / right.ToBigInteger();
    public static BigInteger operator %(ULong2048 left, {t} right) => left.ToBigInteger() % {p};
    public static BigInteger operator %({t} left, ULong2048 right) => {q} % right.ToBigInteger();
    public static BigInteger operator &(ULong2048 left, {t} right) => left.ToBigInteger() & {p};
    public static BigInteger operator &({t} left, ULong2048 right) => {q} & right.ToBigInteger();
    public static BigInteger operator |(ULong2048 left, {t} right) => left.ToBigInteger() | {p};
    public static BigInteger operator |({t} left, ULong2048 right) => {q} | right.ToBigInteger();
    public static BigInteger operator ^(ULong2048 left, {t} right) => left.ToBigInteger() ^ {p};
    public static BigInteger operator ^({t} left, ULong2048 right) => {q} ^ right.ToBigInteger();
    public static bool operator ==(ULong2048 left, {t} right) => left.ToBigInteger() == {p};
    public static bool operator ==({t} left, ULong2048 right) => {q} == right.ToBigInteger();
    public static bool operator !=(ULong2048 left, {t} right) => left.ToBigInteger() != {p};
    public static bool operator !=({t} left, ULong2048 right) => {q} != right.ToBigInteger();
    public static bool operator <(ULong2048 left, {t} right) => left.ToBigInteger() < {p};
    public static bool operator <({t} left, ULong2048 right) => {q} < right.ToBigInteger();
    public static bool operator <=(ULong2048 left, {t} right) => left.ToBigInteger() <= {p};
    public static bool operator <=({t} left, ULong2048 right) => {q} <= right.ToBigInteger();
    public static bool operator >(ULong2048 left, {t} right) => left.ToBigInteger() > {p};
    public static bool operator >({t} left, ULong2048 right) => {q} > right.ToBigInteger();
    public static bool operator >=(ULong2048 left, {t} right) => left.ToBigInteger() >= {p};
    public static bool operator >=({t} left, ULong2048 right) => {q} >= right.ToBigInteger();

"""


TEST_HEADER = """// <auto-generated />
// Generated by scripts/generate_ulong2048_integral_operators.py. Do not hand edit.
#nullable enable

using System.Numerics;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Ricis.Numerics.UnitTests;

[TestClass]
public sealed class ULong2048IntegralOperatorsGeneratedSuite
{
    private static readonly BigInteger Modulus = BigInteger.One << 2048;
    private static readonly ULong2048 Value = ULong2048.FromBigInteger((BigInteger.One << 160) + 12345);
    private static readonly BigInteger ValueBigInteger = Value.ToBigInteger();
    private static BigInteger B(ULong2048 value) => value.ToBigInteger();
    private static BigInteger Wrap(BigInteger value)
    {
        value %= Modulus;
        return value.Sign < 0 ? value + Modulus : value;
    }

"""


def unsigned_literal(t: str) -> str:
    return {
        "byte": "(byte)7", "ushort": "(ushort)7", "uint": "7u", "ulong": "7ul",
        "nuint": "(nuint)7", "UInt128": "(UInt128)7",
    }[t]


def signed_literal(t: str, value: int) -> str:
    raw = str(value)
    return {
        "sbyte": f"(sbyte){raw}", "short": f"(short){raw}", "int": raw, "long": f"{raw}L",
        "nint": f"(nint)({raw})", "Int128": f"(Int128)({raw})",
    }[t]


def unsigned_test(t: str, ordinal: int) -> str:
    literal = unsigned_literal(t)
    return f"""    [TestMethod(\"U2048-INTEGRAL-U{ordinal:02}: {t} symmetric arithmetic bitwise comparison checked and shifts\")]
    public void Unsigned_{t}_Operators()
    {{
        {t} operand = {literal};
        var operandBigInteger = new BigInteger(7);
        Assert.AreEqual(Wrap(ValueBigInteger + operandBigInteger), B(Value + operand));
        Assert.AreEqual(Wrap(operandBigInteger + ValueBigInteger), B(operand + Value));
        Assert.AreEqual(Wrap(ValueBigInteger - operandBigInteger), B(Value - operand));
        Assert.AreEqual(Wrap(operandBigInteger - ValueBigInteger), B(operand - Value));
        Assert.AreEqual(Wrap(ValueBigInteger * operandBigInteger), B(Value * operand));
        Assert.AreEqual(Wrap(operandBigInteger * ValueBigInteger), B(operand * Value));
        Assert.AreEqual(ValueBigInteger / operandBigInteger, B(Value / operand));
        Assert.AreEqual(operandBigInteger / ValueBigInteger, B(operand / Value));
        Assert.AreEqual(ValueBigInteger % operandBigInteger, B(Value % operand));
        Assert.AreEqual(operandBigInteger % ValueBigInteger, B(operand % Value));
        Assert.AreEqual(ValueBigInteger & operandBigInteger, B(Value & operand));
        Assert.AreEqual(operandBigInteger & ValueBigInteger, B(operand & Value));
        Assert.AreEqual(ValueBigInteger | operandBigInteger, B(Value | operand));
        Assert.AreEqual(operandBigInteger | ValueBigInteger, B(operand | Value));
        Assert.AreEqual(ValueBigInteger ^ operandBigInteger, B(Value ^ operand));
        Assert.AreEqual(operandBigInteger ^ ValueBigInteger, B(operand ^ Value));
        Assert.IsTrue(Value > operand && operand < Value && Value != operand && operand != Value);
        Assert.AreEqual(Value << 7, Value << operand);
        Assert.AreEqual(Value >> 7, Value >> operand);
        Assert.AreEqual(Value >>> 7, Value >>> operand);
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue + operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.Zero - operand));
        Assert.ThrowsException<OverflowException>(() => _ = checked(ULong2048.MaxValue * operand));
    }}

"""


def signed_test(t: str, ordinal: int) -> str:
    positive = signed_literal(t, 7)
    negative = signed_literal(t, -7)
    return f"""    [TestMethod(\"U2048-INTEGRAL-S{ordinal:02}: {t} exact signed arithmetic bitwise comparison and shifts\")]
    public void Signed_{t}_Operators()
    {{
        {t} positive = {positive};
        {t} negative = {negative};
        var positiveBigInteger = new BigInteger(7);
        var negativeBigInteger = new BigInteger(-7);
        Assert.AreEqual(ValueBigInteger + positiveBigInteger, Value + positive);
        Assert.AreEqual(positiveBigInteger + ValueBigInteger, positive + Value);
        Assert.AreEqual(ValueBigInteger - positiveBigInteger, Value - positive);
        Assert.AreEqual(positiveBigInteger - ValueBigInteger, positive - Value);
        Assert.AreEqual(ValueBigInteger * negativeBigInteger, Value * negative);
        Assert.AreEqual(negativeBigInteger * ValueBigInteger, negative * Value);
        Assert.AreEqual(ValueBigInteger / negativeBigInteger, Value / negative);
        Assert.AreEqual(negativeBigInteger / ValueBigInteger, negative / Value);
        Assert.AreEqual(ValueBigInteger % negativeBigInteger, Value % negative);
        Assert.AreEqual(negativeBigInteger % ValueBigInteger, negative % Value);
        Assert.AreEqual(ValueBigInteger & negativeBigInteger, Value & negative);
        Assert.AreEqual(negativeBigInteger & ValueBigInteger, negative & Value);
        Assert.AreEqual(ValueBigInteger | negativeBigInteger, Value | negative);
        Assert.AreEqual(negativeBigInteger | ValueBigInteger, negative | Value);
        Assert.AreEqual(ValueBigInteger ^ negativeBigInteger, Value ^ negative);
        Assert.AreEqual(negativeBigInteger ^ ValueBigInteger, negative ^ Value);
        Assert.IsTrue(Value > negative && negative < Value && Value != negative && negative != Value);
        Assert.AreEqual(Value << 7, Value << positive);
        Assert.AreEqual(Value >> 7, Value >> positive);
        Assert.AreEqual(Value >>> 7, Value >>> positive);
        Assert.AreEqual(Value >> 7, Value << negative);
    }}

"""


def render_tests() -> str:
    body = TEST_HEADER
    for index, t in enumerate(UNSIGNED, start=1):
        body += unsigned_test(t, index)
    for index, t in enumerate(SIGNED, start=1):
        body += signed_test(t, index)
    return body + "}\n"


def render() -> str:
    body = HEADER
    for t in UNSIGNED:
        body += unsigned_block(t)
    for t in SIGNED:
        body += signed_block(t)
    body += "}\n"
    return body


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render()
    generated_tests = render_tests()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != generated or not TEST_TARGET.exists() or TEST_TARGET.read_text() != generated_tests:
            print("ULONG2048_INTEGRAL_OPERATORS_STALE")
            return 1
        print("ULONG2048_INTEGRAL_OPERATORS_VERIFY_PASS")
        return 0
    TARGET.write_text(generated)
    TEST_TARGET.write_text(generated_tests)
    print("ULONG2048_INTEGRAL_OPERATORS_GENERATED")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
