#!/usr/bin/env python3
"""Generate independent MSTest methods from the canonical RICIS regression catalog."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


HEADER = """// <auto-generated />
// Generated by scripts/generate_mstest_regression_adapter.py from
// RicisRegressionTestCatalog. Do not edit this file manually.
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Ricis.Core.UnitTests;

[TestClass]
public sealed class RicisRegressionCatalogMSTestAdapter
{
"""
FOOTER = "}\n"


def escape_csharp(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def canonical_names(root: Path) -> list[str]:
    result = subprocess.run(
        [
            "dotnet",
            "run",
            "--project",
            "RegressionTests/Ricis.Core.RegressionTests.csproj",
            "--configuration",
            "Release",
            "--",
            "--list-tests",
        ],
        cwd=root,
        check=True,
        capture_output=True,
        encoding="utf-8",
    )
    names = [line.strip() for line in result.stdout.splitlines() if line.strip()]
    if not names:
        raise RuntimeError("Canonical regression catalog returned no test names.")
    if len(names) != len(set(names)):
        raise RuntimeError("Canonical regression catalog contains duplicate test names.")
    return names


def render(names: list[str]) -> str:
    methods: list[str] = []
    for index, name in enumerate(names):
        methods.append(
            "    [TestMethod(\"{title}\")]\n"
            "    [TestCategory(\"Regression\")]\n"
            "    public void Regression_{number:03d}() => "
            "RicisRegressionTestCatalog.Tests[{index}].Body();\n".format(
                title=escape_csharp(name), number=index + 1, index=index
            )
        )
    return HEADER + "\n".join(methods) + FOOTER


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail when generated source is stale.")
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    destination = root / "UnitTests" / "RicisRegressionCatalogMSTestAdapter.generated.cs"
    generated = render(canonical_names(root))

    if args.check:
        if not destination.is_file() or destination.read_text(encoding="utf-8") != generated:
            print("MSTEST_REGRESSION_ADAPTER_VERIFY_FAIL: generated adapter is stale.")
            return 1
        print(f"MSTEST_REGRESSION_ADAPTER_VERIFY_PASS: {generated.count('[TestMethod(')} independent tests")
        return 0

    destination.write_text(generated, encoding="utf-8")
    print(f"MSTEST_REGRESSION_ADAPTER_GENERATED: {generated.count('[TestMethod(')} independent tests")
    return 0


if __name__ == "__main__":
    sys.exit(main())
